#!/usr/bin/ruby

require 'rubygems'
require 'rake'
require 'rake/clean'
require 'rake/gempackagetask'

task :default => [:package]

# Create the gem specification for packaging
spec = Gem::Specification.new do |s|
    s.name = %q{li}
    s.version = /(Version: )(.*)/.match(File.read("../build/specs/li.spec"))[2]
    s.author = "Red Hat"
    s.email = %q{libra-list@redhat.com}
    s.summary = %q{Libra client tools}
    s.homepage = %q{https://www.redhat.com}
    s.description = %q{Libra client tools}
    s.files = FileList['lib/**/*.rb', 'bin/*', 'conf/*'].to_a
    s.files += %w(LICENSE README Rakefile)
    s.executables = ['rhc-create-app', 'rhc-create-domain', 'rhc-ctl-app', 'rhc-snapshot', 'rhc-user-info']
    s.add_dependency('json')
end

# Define a :package task that bundles the gem
Rake::GemPackageTask.new(spec) do |pkg|
  pkg.need_tar = false
end

# Add the 'pkg' directory to the clean task
CLEAN.include("pkg")
