#!/usr/bin/ruby

require 'rubygems'
require 'rake'
require 'rake/clean'
require 'rake/gempackagetask'

task :default => [:package]

# Create the gem specification for packaging
spec = Gem::Specification.new do |s|
    s.name = %q{rhc}
    s.version = /(Version: )(.*)/.match(File.read("client.spec"))[2]
    s.author = "Red Hat"
    s.email = %q{openshift@redhat.com}
    s.summary = %q{OpenShift Express Client Tools}
    s.homepage = %q{https://openshift.redhat.com/app/express}
    s.description = %q{OpenShift Express Client Tools}
    s.files = FileList['lib/**/*.rb', 'bin/*', 'conf/*'].to_a
    s.files += %w(LICENSE README Rakefile)
    s.executables = ['rhc-create-app', 'rhc-create-domain', 'rhc-ctl-app', 'rhc-snapshot', 'rhc-user-info', 'rhc-tail-files']
    s.add_dependency('json_pure')
    s.add_dependency('parseconfig')
end

# Define a :package task that bundles the gem
Rake::GemPackageTask.new(spec) do |pkg|
  pkg.need_tar = false
end

# Add the 'pkg' directory to the clean task
CLEAN.include("pkg")
