#!/usr/bin/env ruby
# Copyright © 2010 Jim Jagielski All rights reserved
# Copyright © 2010 Mike McGrath All rights reserved
# Copyright © 2010 Red Hat, Inc. All rights reserved

# This copyrighted material is made available to anyone wishing to use, modify,
# copy, or redistribute it subject to the terms and conditions of the GNU
# General Public License v.2.  This program is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY expressed or implied, including the
# implied warranties of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.  You should have
# received a copy of the GNU General Public License along with this program;
# if not, write to the Free Software Foundation, Inc., 51 Franklin Street,
# Fifth Floor, Boston, MA 02110-1301, USA. Any Red Hat trademarks that are
# incorporated in the source code or documentation are not subject to the GNU
# General Public License and may only be used or replicated with the express
# permission of Red Hat, Inc.

require "rubygems"
require "uri"
require "net/http"
require "net/https"
require "getoptlong"
require "json"
require 'parseconfig'

config_path = File.exists?('client.conf') ? 'client.conf' : '/etc/libra/client.conf'

unless File.exists?("#{ENV['HOME']}/.li")
    file = File.open("#{ENV['HOME']}/.li", 'w')
    file.close
end

begin
    @global_config = ParseConfig.new(config_path)
    @local_config = ParseConfig.new("#{ENV['HOME']}/.li")
rescue Errno::EACCES => e
    puts "Could not open config file: #{e.message}"
    exit 253
end

#
# Check for proxy environment
#
if ENV['http_proxy']
    host, port = ENV['http_proxy'].split(':')
    @http = Net::HTTP::Proxy(host, port)
else
    @http = Net::HTTP
end

#
# Check for local var in ~/.li use it, else use /etc/libra/client.conf
#
def get_var(var)
    @local_config.get_value(var) ? @local_config.get_value(var) : @global_config.get_value(var)
end

#
# print help
#
def p_usage
    namespace = @local_config.get_value('default_namespace') ? "Default: #{@local_config.get_value('default_namespace')}" : "(required)"
    puts <<USAGE

Usage: rhc-user-info
Display information about a user

  -n|--namespace   namespace    RHCloud namespace (alphanumeric) (#{namespace})
  -a|--apps                     List applications for namespace
  -i|--info                     Show user info
  -d|--debug                    Print Debug info
  -h|--help                     Show Usage info

USAGE
exit 255
end

def validate_email(email)
    if email =~ /([^@]+)@([a-zA-Z0-9\.])+\.([a-zA-Z]{2,3})/
        if $1 =~ /[^a-zA-Z0-9\.]/
            return false
        else
            return true
        end
    else
        return false
    end
end

opts = GetoptLong.new(
    ["--debug", "-d", GetoptLong::NO_ARGUMENT],
    ["--help",  "-h", GetoptLong::NO_ARGUMENT],
    ["--apps",  "-a", GetoptLong::NO_ARGUMENT],
    ["--info",  "-i", GetoptLong::NO_ARGUMENT],
    ["--namespace",  "-n", GetoptLong::REQUIRED_ARGUMENT]
)

# Pull in configs from files
li_server = get_var('li_server')
debug = get_var('debug') == 'false' ? nil : get_var('debug')
libra_domain = get_var('libra_domain')

libra_kfile = "#{ENV['HOME']}/.ssh/libra_id_rsa"
libra_kpfile = "#{ENV['HOME']}/.ssh/libra_id_rsa.pub"

opt = {}
opts.each do |o, a|
    opt[o[2..-1]] = a.to_s
end

if opt["help"]
    p_usage
end

if opt["debug"]
    debug = true
end

opt["namespace"] = @local_config.get_value('default_namespace') unless opt["namespace"]

if opt["namespace"]
    if opt["namespace"] =~ /[^0-9a-zA-Z]/
        puts "namespace contains non-alphanumeric characters!"
        p_usage
    end
else
    puts "Namespace is required"
    p_usage
end

opt['apps'] = true if not opt['info'] and not opt['apps']

puts "Contacting https://#{li_server}"
json_data = JSON.generate(
                {'namespace' => opt['namespace']})
puts "DEBUG: Json string: #{json_data}" if debug

url = URI.parse("https://#{li_server}/php/user_info.php")
req = @http::Post.new(url.path)

req.set_form_data({'json_data' => json_data})
http = @http.new(url.host, url.port)
if url.scheme == "https"
  http.use_ssl = true
  http.verify_mode = OpenSSL::SSL::VERIFY_NONE
end
response = http.start {|http| http.request(req)}

puts "DEBUG:" if debug
p response if debug
json_resp = JSON.parse(response.body);

unless json_resp['return'].to_s.strip == "0"
    puts "Problem with server. Response code was #{response.code}"
    puts "HTTP response from server is #{response.body}"
    exit 255
end

if debug
    puts "HTTP response from server is #{response.body}"
end
user_info = JSON.parse(json_resp['stdout'].to_s)

if user_info['user_info']['uuid'] != @local_config.get_value(opt["namespace"])
    puts
    puts "WARNING!  The UUID in your ~/.li file is either missing or incorrect."
    puts "Please ensure the following line exists in ~/.li"
    puts
    puts "#{opt['namespace']}=#{user_info['user_info']['uuid']}"
    puts
end

if opt['info']
    puts "User Info"
    puts "========="
    puts "Namespace: #{user_info['user_info']['username']}"
    puts "    UUID: #{user_info['user_info']['uuid']}"
    puts "   email: #{user_info['user_info']['email']}"
    puts " ssh_key: #{user_info['user_info']['ssh_key']}"
end

if opt['apps']
    puts "\n\n" if opt['info']

    puts "Application Info"
    puts "================"
    user_info['app_info'].each do |key, val|
        puts key
        puts "  Framework: #{val['framework']}"
        puts "   Creation: #{val['creation_time']}"
        puts "    Git URL: ssh://#{user_info['user_info']['uuid']}@#{key}.#{user_info['user_info']['username']}.#{libra_domain}/~/git/#{key}.git/"
        puts " Public URL: http://#{key}.#{user_info['user_info']['username']}.#{libra_domain}/"
        puts ""
    end
    
end

exit 0
