<?php

include_once('redhat_ideas.features.inc');

function redhat_ideas_menu() {
  $items['ideas'] = array(
    'page callback' => redhat_ideas_page,
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  
  return $items;
}

function redhat_ideas_page() {
  global $base_url;
  $content .= '<p>View the current feature requests below, browse our implemented ideas down below, or submit a new one to the OpenShift team!</p>
<div class="new-post-button"><a class="btn btn-create" href="/community/node/add/idea">Submit an Idea</a></div>';
  $content .= '<div class="row-fluid"><div class="span6"><h2>Top Ideas</h2>';
  $content .= views_embed_view('Ideas', 'block_1');
  $content .= '</div><section class="span6"><h2>Recent Ideas</h2>';
  $content .= views_embed_view('Ideas', 'block_3');
  $content .= '</section></div>';
  $content .= '<section>';
  $content .= '<h2>Implemented Ideas</h2>';
  $content .= views_embed_view('Ideas', 'block_2');
  $content .= '</section>';
  return $content;
}

function vud_views_query_alter(&$view, &$query) {
    if($view->name == 'Ideas'){
        $query->fields['votingapi_cache_node_points_vote_sum_value']['table'] = 'IFNULL(votingapi_cache_node_points_vote_sum';
        $query->fields['votingapi_cache_node_points_vote_sum_value']['field'] = 'value, 0)';
    }
}
