#!/bin/bash

[ ! -z "$PSQL_LIB_UTIL" ] && return 0
PSQL_LIB_UTIL=true

function start_postgres {
    /bin/su -s /bin/sh "$uuid" -c "runcon -t libra_t -l $mcs_level $PSQL_DIR/${application}_postgresql_ctl.sh start"
    wait_to_start
}

function wait_to_start {
    i=0
    while (( ! echo "$OPENSHIFT_DB_PASSWORD\n\\l;\n\\q\n" | psql -u $OPENSHIFT_DB_USERNAME -h $OPENSHIFT_DB_HOST -p $OPENSHIFT_DB_PORT > /dev/null 2>&1) || [ ! -f ${PSQL_DIR}/pid/postgres.pid ]) && [ $i -lt 10 ]
    do
        sleep 1
        i=$(($i + 1))
    done
}


function stop_mysql {
    /bin/su -s /bin/sh "$uuid" -c "runcon -t libra_t -l $mcs_level $PSQL_DIR/${application}_postgresql_ctl.sh stop"
}

function start_postgresql_as_user {
    ${OPENSHIFT_DB_CTL_SCRIPT} start
}

function stop_postgresql_as_user {
    ${OPENSHIFT_DB_CTL_SCRIPT} stop
    sleep 1
}

function wait_to_start_as_user {
    if [ -n "$OPENSHIFT_DB_USERNAME" ]
    then
        i=0
        sleep 1
        while (( ! echo "$OPENSHIFT_DB_PASSWORD\n\\l;\n\\q\n" | psql -u $OPENSHIFT_DB_USERNAME -h $OPENSHIFT_DB_HOST -p $OPENSHIFT_DB_PORT > /dev/null 2>&1) || [ ! -f ${PSQL_DIR}/pid/postgres.pid ]) && [ $i -lt 10 ]
        do
            sleep 1
            i=$(($i + 1))
        done
    fi
}
