#!/bin/bash

# Start the application httpd instance

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Start a running application"

    echo "$0 $@" | logger -p local0.notice -t stickshift_jboss_publish_git_url
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

#
# echo ssh location
# 
source "/etc/stickshift/stickshift-node.conf"
source ${GEAR_BASE_DIR}/$3/.env/OPENSHIFT_GEAR_UUID # yes its the same, this is a sanity check
source ${GEAR_BASE_DIR}/$3/.env/OPENSHIFT_GEAR_DNS
source ${GEAR_BASE_DIR}/$3/.env/OPENSHIFT_GEAR_NAME
echo "ssh://${OPENSHIFT_GEAR_UUID}@${OPENSHIFT_GEAR_DNS}/~/git/${OPENSHIFT_GEAR_NAME}.git/"
