#!/usr/bin/ruby
#
# Test and install Libra Node tools
#
require 'rubygems'
require 'rake'

require 'rake/clean'
require 'rake/gempackagetask'

require 'rake/testtask'

task :default => [:package]

# Create the gem specification for packaging
spec = Gem::Specification.new do |s|
  s.name = %q{li-node-tools}
  s.version = /(Version: )(.*)/.match(File.read("../../build/specs/li.spec"))[2]
  s.author = "Mark lamourine"
  s.email = %q{markllama@redhat.com}
  s.summary = %q{Libra node management tools}
  s.homepage = %q{https://engineering.redhat.com/trac/Libra}
  s.description = %q{Library and tools to view and manage a Libra node}
  s.files = FileList['lib/**/*.rb', 'bin/*'].to_a
  s.executables = ['li-accounts', 'li-applications']
  s.add_dependency('json')
  s.add_dependency('nokogiri')  # XML processing
  # MAL 20110323 - not sure what these are for.  Uncomment when you need them.
  #s.add_development_dependency("rspec")
  #s.add_development_dependency("cucumber")
end

# Define a :package task that bundles the gem
Rake::GemPackageTask.new(spec) do |pkg|
  pkg.need_tar = false
end

# Add the 'pkg' directory to the clean task
CLEAN.include("pkg")

Rake::TestTask.new do |test|
  test.libs << "unittest"
  test.test_files = Dir[ "unittest/test*.rb" ]
  test.verbose = false
end

task :install do
  # copy lib files to ruby lib directory

  # copy bin files to libexec/li/node-tools/

  # copy doc files to share/doc/<pkgname>/
end

