#!/usr/bin/env ruby

$:.unshift(File.dirname(__FILE__) + '/../lib')
require 'rubygems'
require 'libra'

include Libra

options = {}
OptionParser.new do |opts|
    opts.define_head "Adjust libra cluster capacity"
    opts.banner = "Usage: li-capacity"
end.parse!

# Adjust the capacity of the libra cluster if needed
Libra.adjust_capacity
