#!/bin/bash

# Start the application httpd instance

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Start a running application"

    echo "$0 $@" | logger -p local0.notice -t stickshift_node_publish_git_url
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

source "/etc/stickshift/stickshift-node.conf"
#
# echo ssh location
# 
source ${GEAR_BASE_DIR}/$3/.env/OPENSHIFT_APP_UUID # yes its the same, this is a sanity check
source ${GEAR_BASE_DIR}/$3/.env/OPENSHIFT_APP_DNS
source ${GEAR_BASE_DIR}/$3/.env/OPENSHIFT_APP_NAME
echo "ssh://${OPENSHIFT_APP_UUID}@${OPENSHIFT_APP_DNS}/~/git/${OPENSHIFT_APP_NAME}.git/"
