#!/bin/bash

# Confirms all required diy bits are in place or fails

set -e

CART_DIR=/usr/libexec/li/cartridges
source ${CART_DIR}/abstract/info/lib/util

load_node_conf

[ -z "$CARTRIDGE_DIR" ] && CARTRIDGE_DIR="/usr/libexec/li/cartridges/diy-0.1/"

function print_help {
    echo "Usage: uuid"
    exit 1
}

function quit {
    echo -e "$1" 1>&2
    exit 5
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done

[ $# -eq 1 ] || print_help

uuid=$1

rpm -q rhc-cartridge-raw-0.1 httpd > /dev/null || quit "Missing packages"
[ -d "$CARTRIDGE_DIR" ] || quit "Missing cartridge dir: $CARTRIDGE_DIR"
