#!/bin/bash

# Copyright © 2010 Mike McGrath All rights reserved
# Copyright © 2010 Red Hat, Inc. All rights reserved

# This copyrighted material is made available to anyone wishing to use, modify,
# copy, or redistribute it subject to the terms and conditions of the GNU
# General Public License v.2.  This program is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY expressed or implied, including the
# implied warranties of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.  You should have
# received a copy of the GNU General Public License along with this program;
# if not, write to the Free Software Foundation, Inc., 51 Franklin Street,
# Fifth Floor, Boston, MA 02110-1301, USA. Any Red Hat trademarks that are
# incorporated in the source code or documentation are not subject to the GNU
# General Public License and may only be used or replicated with the express
# permission of Red Hat, Inc.

# Prepare to move to a new ip

# Exit on any errors
set -e

CART_DIR=/usr/libexec/li/cartridges

source ${CART_DIR}/abstract/info/lib/util
source ${CART_DIR}/abstract/info/lib/selinux
source ${CART_DIR}/abstract/info/lib/apache
source ${CART_DIR}/abstract/info/lib/network

load_node_conf

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done

[ $# -eq 3 ] || print_help

namespace=`basename $2`
application="$1"
uuid=$3

setup_basic_vars

CART_INFO_DIR=$CART_DIR/embedded/mysql-5.1/info
source ${CART_INFO_DIR}/lib/util

MYSQL_DIR="$APP_HOME/mysql-5.1/"

. $APP_HOME/.env/OPENSHIFT_INTERNAL_IP
IP=$OPENSHIFT_INTERNAL_IP

. $APP_HOME/.env/OPENSHIFT_DB_PORT

. $APP_HOME/.env/OPENSHIFT_DB_PASSWORD
. $APP_HOME/.env/OPENSHIFT_DB_USERNAME
if [ "$OPENSHIFT_DB_PASSWORD" = "NOT_AVAILABLE" ]
then
    error "Can not move mysql without OPENSHIFT_DB_PASSWORD" 188
else

start_mysql

    echo "
grant all on *.* to '$OPENSHIFT_DB_USERNAME'@'%' identified by '$OPENSHIFT_DB_PASSWORD' with grant option;
flush privileges;" | mysql -u $OPENSHIFT_DB_USERNAME -P $OPENSHIFT_DB_PORT -h $IP --password="$OPENSHIFT_DB_PASSWORD" -S "${MYSQL_DIR}/socket/mysql.sock" mysql > /dev/null || error "Failed to setup root user with wildcard ip" 187

stop_mysql

fi