#!/bin/bash

[ ! -z "$MYSQL_LIB_UTIL" ] && return 0
MYSQL_LIB_UTIL=true

function start_mysql {
    super_run_as_user "$MYSQL_DIR/${application}_mysql_ctl.sh start"
    wait_to_start
}

function wait_to_start {
    i=0
    while (( ! echo ";" | mysql -u root -S "${MYSQL_DIR}/socket/mysql.sock" > /dev/null 2>&1) || [ ! -f ${MYSQL_DIR}/pid/mysql.pid ]) && [ $i -lt 10 ]
    do
        sleep 1
        i=$(($i + 1))
    done
}


function stop_mysql {
    super_run_as_user "$MYSQL_DIR/${application}_mysql_ctl.sh stop"
}

function start_mysql_as_user {
    # FIXME: Need to start mysql on the right gear.
    if [ -n "$OPENSHIFT_DB_GEAR_USERHOST" ]; then
       echo "TBD: start mysql on its gear"
       # ssh $OPENSHIFT_DB_GEAR_USERHOST "$OPENSHIFT_DB_CTL_SCRIPT"
    fi

    ${OPENSHIFT_DB_CTL_SCRIPT} start
}

function stop_mysql_as_user {
    ${OPENSHIFT_DB_CTL_SCRIPT} stop
    sleep 1
}

function wait_to_start_as_user {
    if [ -n "$OPENSHIFT_DB_USERNAME" ]
    then
        i=0
        sleep 1
        while (( ! echo ";" | mysql -h $OPENSHIFT_DB_HOST -P $OPENSHIFT_DB_PORT -u $OPENSHIFT_DB_USERNAME --password="$OPENSHIFT_DB_PASSWORD" > /dev/null 2>&1) || [ ! -f ${MYSQL_DIR}/pid/mysql.pid ]) && [ $i -lt 10 ]
        do
            sleep 1
            i=$(($i + 1))
        done
    fi
}
