#!/bin/bash

[ ! -z "$MYSQL_LIB_UTIL" ] && return 0
MYSQL_LIB_UTIL=true

function start_mysql {
    /bin/su -s /bin/sh "$uuid" -c "runcon -t libra_t -l $mcs_level $MYSQL_DIR/${application}_mysql_ctl.sh start"
    i=0
    while ( ! echo ";" | mysql -u root ) && [ $i -lt 30 ]
    do
        sleep .3
        i=$(($i + 1))
    done
}

function stop_mysql {
    /bin/su -s /bin/sh "$uuid" -c "runcon -t libra_t -l $mcs_level $MYSQL_DIR/${application}_mysql_ctl.sh stop"
}