#!/bin/bash
#
# libra-datastore This shell script can configure/start/stop libra datastore service
#
# Author:       Ravi <rpenta@redhat.com>
# Edited original mongod init script 
#
# chkconfig:    345 89 01
#
# description:  Start and stop mongod service with given params
# processname:  NA
#

# source function library
. /etc/rc.d/init.d/functions

exec="/usr/bin/mongod"
prog="mongod"
logfile="/var/log/mongodb/mongodb.log"
options="  --auth --nojournal --smallfiles -f /etc/mongodb.conf"

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

lockfile="/var/lock/subsys/mongod"

start() {
    [ -x $exec ] || exit 5
    echo -n $"Starting $prog: "
    daemon --user mongodb "$exec --quiet $options run >> $logfile 2>&1 &"
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_configure() {
    # Start mongod server
    start
    retry_cnt=0
    while true; do
        sleep 1
        rh_status_q
        if [ $? -eq 0 ]; then
            break;
        fi
        $retry_cnt += 1
        echo $retry_cnt
    	if [ $retry_cnt -ge 10 ]; then
            echo "Unable to start mongod server"
            exit 1
        fi
    done
    # Setup user
    echo "use admin
          db.addUser(\"libra\", \"momo\")
          exit
         "  | mongo
    # Stop mongod server
    stop
}

rh_status() {
    # run checks to determine if the service is running or use generic status
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    configure)
        rh_configure
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload|configure}"
        exit 2
esac
exit $?
