#!/bin/sh
#
# libra-proxy
#
# chkconfig:   345 85 15
# description:  HAProxy is a free, very fast and reliable solution \
#               offering high availability, load balancing, and \
#               proxying for TCP and  HTTP-based applications
# processname: haproxy
# config:      /etc/libra/libra-proxy.cfg
# pidfile:     /var/run/libra-proxy.pid

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0

exec="/usr/sbin/haproxy"
prog=$(basename $exec)

[ -e /etc/sysconfig/libra-proxy ] && . /etc/sysconfig/libra-proxy

lockfile=/var/lock/subsys/libra-proxy
pidfile=/var/run/libra-proxy.pid
cfgfile=/etc/libra/libra-proxy.cfg


check() {
    $exec -c -V -f $cfgfile
}

fixaddr() {
    # Fix eth0's address in case it was changed by the cloud provider
    baddr=`ip -4 addr show dev eth0 scope global | sed -r -n '/inet/ { s/^.*inet ([0-9\.]+).*/\1/; p }' | head -1`
    sed -i -r -e '/^[^\#]*bind/ { /127\.[0-9\.]+:/ b; s/([0-9\.]+):/'"$baddr"':/ }' $cfgfile
}

start() {
    fixaddr
    $exec -c -q -f $cfgfile
    if [ $? -ne 0 ]; then
        echo "Errors in configuration file, check with libra-proxy check."
        return 1
    fi
 
    echo -n $"Starting libra-proxy: "
    # start it up here, usually something like "daemon $exec"
    daemon --pidfile $pidfile $exec -D -f $cfgfile -p $pidfile
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping libra-proxy: "
    # stop it here, often "killproc $prog"
    killproc -p $pidfile $prog 
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    $exec -c -q -f $cfgfile
    if [ $? -ne 0 ]; then
        echo "Errors in configuration file, check with libra-proxy check."
        return 1
    fi
    stop
    start
}

reload() {
    $exec -c -q -f $cfgfile
    if [ $? -ne 0 ]; then
        echo "Errors in configuration file, check with libra-proxy check."
        return 1
    fi
    echo -n $"Reloading libra-proxy: "
    $exec -D -f $cfgfile -p $pidfile -sf $(cat $pidfile)
    retval=$?
    echo
    return $retval
}

force_reload() {
    restart
}

fdr_status() {
    status -p $pidfile $prog
}

case "$1" in
    start|stop|restart|reload)
        $1
        ;;
    force-reload)
        force_reload
        ;;
    check)
        check
        ;;
    status)
        fdr_status
        ;;
    condrestart|try-restart)
  	[ ! -f $lockfile ] || restart
	;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|try-restart|reload|force-reload}"
        exit 2
esac
