#!/bin/bash
#
# libra         This shell script starts libra services
#
# Author:       Mike McGrath <mmcgrath@redhat.com>
#
# chkconfig:    345 89 01
#
# description:  Get information about the host
# processname:  NA
#

# source function library
. /etc/rc.d/init.d/functions
. /etc/libra/node.conf

lockfile=/var/lock/subsys/libra

RETVAL=0
GROUP_RETVAL=0

start() {
    echo "Getting Libra info "
    instance_id=$(wget -qO- http://169.254.169.254/latest/meta-data/instance-id)
    [ -z $public_ip ] && public_ip=$(wget -qO- http://169.254.169.254/latest/meta-data/public-ipv4)
    if [ ! "$public_ip" ]; then
      for i in {1..60}
      do
        # Sometimes it takes a while for the public ip to be published
        sleep 10
        public_ip=$(wget -qO- http://169.254.169.254/latest/meta-data/public-ipv4)
        if [ "$public_ip" ]; then
          break
        fi
      done
    fi

    echo_success
    cat <<EOF > /etc/libra/node_data.conf
instance_id="$instance_id"
public_ip="$public_ip"
EOF
    return
}

stop() {
    return
}

restart() {
    stop
    start
}

case "$1" in
  start)
    start
    ;;
  stop) 
    stop
    ;;
  restart|force-reload)
    restart
    ;;
  reload)
    ;;
  status)
    echo "Checking Libra Services: "
    # This won't scale forever, but works fine in the '100 or so' range
    for ctl_script in /var/lib/libra/*/*/*_ctl.sh
    do
        script_name=$(basename $ctl_script)
        echo -n $"    Checking http for ${script_name%_ctl.sh}"
        daemon --pidfile=httpd_${script_name} $ctl_script status
        RETVAL=$?
        echo
        if [ $RETVAL -eq 0 ]
        then
            echo_success
        else
            GROUP_RETVAL=$(($GROUP_RETVAL+1))
            echo_failure
        fi
    done
    echo
    return $GROUP_RETVAL
    ;;
  *)
    echo $"Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart}"
    exit 1
esac

exit $RETVAL
