#!/usr/bin/python -tt

import sys, os
import syslog

commands = {
    "git-receive-pack": "/usr/bin/git-receive-pack",
    "git-upload-pack": "/usr/bin/git-upload-pack",
}

if __name__ == '__main__':
    orig_cmd = os.environ.get('SSH_ORIGINAL_COMMAND')
    if not orig_cmd:
        print "Need a command"
        sys.exit(1)
    allargs = orig_cmd.split()
    try:
        basecmd = os.path.basename(allargs[0])
        cmd = commands[basecmd]
    except:
        syslog.syslog("Invalid command %s" % orig_cmd)
        sys.stderr.write("Invalid command %s" % orig_cmd)
        sys.exit(2)

    if basecmd in ('git-receive-pack', 'git-upload-pack'):
        # git repositories need to be parsed specially
        thearg = ' '.join(allargs[1:])
        if thearg[0] == "'" and thearg[-1] == "'":
            thearg = thearg.replace("'","")
        thearg = thearg.replace("\\'", "")
        thearg = thearg.replace("//", "/")

        # replace leading tilde (~) with user's home path
        realpath = os.path.expanduser(thearg)
        if not realpath.startswith('/var/lib/libra/'):
            syslog.syslog("Invalid repository: not in libra_root - %s: (%s)" % 
                          (thearg, realpath))
            print "Invalid repository %s: not in libra_root" % thearg
            sys.exit(3)

        if not os.path.isdir(realpath):
            syslog.syslog("Invalid repository %s (%s)" % 
                          (thearg, realpath))
            print "Invalid repository %s: not a directory" % thearg
            sys.exit(3)


        allargs = [thearg]
    os.execv(cmd, [cmd] + allargs)
    sys.exit(1)

