require 'rubygems'
require 'rake'
require 'rake/clean'
require 'rake/gempackagetask'

CLEAN.include("pkg")

spec = Gem::Specification.new do |s|
    s.name = %q{li-controller}
    s.version = "0.05"
    s.date = %q{2011-01-12}
    s.author = "Matt Hicks"
    s.email = %q{mhicks@redhat.com}
    s.summary = %q{Libra server side controller}
    s.homepage = %q{https://engineering.redhat.com/trac/Libra}
    s.description = %q{Libra server side controller}
    s.files = FileList['conf/*', 'lib/**/*.rb', 'bin/*'].to_a
    s.executables = ['mc-libra', 'new-user']
    s.add_dependency('parseconfig')
    s.add_dependency('json')
    s.add_dependency('right_aws')
    s.add_development_dependency("rspec")
    s.add_development_dependency("cucumber")
end

task :default => [:package]

Rake::GemPackageTask.new(spec) do |pkg|
    pkg.need_tar = true
end

# Start development dependencies
begin
    require 'spec/rake/spectask'

    desc "Run all rspec tests"
    Spec::Rake::SpecTask.new(:spec) do |t|
        t.spec_opts << '--color'
        t.spec_opts << '--format specdoc'
        t.spec_files = FileList['spec/**/*.rb']
    end

    require "cucumber/rake/task"

    desc "Run all cucumber tests"
    Cucumber::Rake::Task.new(:cuc) do |t|
      t.cucumber_opts = ["features"]
    end
rescue LoadError
    # Don't list the tasks if dependencies aren't installed
end
