require 'rubygems'
require 'rake'

# Require these within the namespace
require 'rake/clean'
require 'rake/gempackagetask'

# Setup the gem specification for packaging gems
# Read the version from the RPM
spec = Gem::Specification.new do |s|
    s.name = %q{li-controller}
    s.version = /Version: (\d+\.\d+)/.match(File.read("../../packaging/li.spec"))[1]
    s.author = "Matt Hicks"
    s.email = %q{mhicks@redhat.com}
    s.summary = %q{Libra server side controller}
    s.homepage = %q{https://engineering.redhat.com/trac/Libra}
    s.description = %q{Libra server side controller}
    s.files = FileList['conf/*', 'lib/**/*.rb', 'bin/*'].to_a
    s.executables = ['mc-rhc-cartridge-do', 'rhc-new-user', 'rhc-capacity', 'rhc-get-user-info']
    s.add_dependency('parseconfig')
    s.add_dependency('json')
    s.add_dependency('aws')
    s.add_development_dependency("rspec")
    s.add_development_dependency("cucumber")
end


# Define a :package task that bundles the gem
Rake::GemPackageTask.new(spec) do |pkg|
  pkg.need_tar = false
end

# Add the 'pkg' directory to the clean task
CLEAN.include("pkg")


# Set the default to :package
task :default => :package
