require 'rubygems'
require 'rake'

# Require these within the namespace
require 'rake/clean'
require 'rake/gempackagetask'

# Setup the gem specification for packaging gems
spec = Gem::Specification.new do |s|
    s.name = %q{li-controller}
    s.version = "0.11"
    s.date = %q{2011-01-20}
    s.author = "Matt Hicks"
    s.email = %q{mhicks@redhat.com}
    s.summary = %q{Libra server side controller}
    s.homepage = %q{https://engineering.redhat.com/trac/Libra}
    s.description = %q{Libra server side controller}
    s.files = FileList['conf/*', 'lib/**/*.rb', 'bin/*'].to_a
    s.executables = ['mc-libra', 'new-user', 'li-capacity']
    s.add_dependency('parseconfig')
    s.add_dependency('json')
    s.add_dependency('right_aws')
    s.add_development_dependency("rspec")
    s.add_development_dependency("cucumber")
end


# Define a :package task that bundles the gem
Rake::GemPackageTask.new(spec) do |pkg|
  pkg.need_tar = false
end

# Add the 'pkg' directory to the clean task
CLEAN.include("pkg")

# Add an install method that
desc 'Install a clean version of the new li-controller gem'
task :install => [:clean, :package] do
  # Force uninstallation of the gem - including binaries
  sh "sudo gem uninstall -ax li-controller"

  # Install the gem
  sh "sudo gem install pkg/li-controller-#{spec.version}.gem"
end

#
# Start development dependencies - if the dependencies
# are not installed, these tasks won't be listed
#
begin
    require 'spec/rake/spectask'

    desc "Run all rspec tests"
    Spec::Rake::SpecTask.new(:spec) do |t|
        t.spec_opts << '--color'
        t.spec_opts << '--format specdoc'
        t.spec_files = FileList['spec/**/*.rb']
    end

    require "cucumber/rake/task"

    desc "Run all cucumber core tests"
    Cucumber::Rake::Task.new(:cuc) do |t|
      t.cucumber_opts = "--tags ~@sprint"
    end

    desc "Run a cucumber sprint test (supply the sprint number as an argument)"
    task :cuc_sprint, :sprint_num do |t, args|
      Cucumber::Rake::Task.new(:cuc_sprint) do |t|
        t.cucumber_opts = "--tags @sprint#{args[:sprint_num]}"
      end
    end

rescue LoadError
    # Ignore error - this allows rake to be run from
    # non-development servers
end

# Set the default to :package
task :default => :package
