#!/bin/sh

# Set the OS / browser combinations
export SAUCE_OS=$1
export SAUCE_BROWSER=$2
export SAUCE_BROWSER_VERSION=$3

# Launch a host and save the hostname
export SAUCE_HOSTNAME=`${WORKSPACE}/build/devenv launch ${JOB_NAME}_${BUILD_NUMBER} | grep 'Hostname:' | awk '{print $2}'`
export SAUCE_BROWSER_URL="https://${SAUCE_HOSTNAME}"

# Sync the code
${WORKSPACE}/build/devenv sync ${SAUCE_HOSTNAME} --clean_metadata

# Run the Sauce Labs tests
ruby ts_web
