<?php

include_once('redhat_ideas.features.inc');

function redhat_ideas_menu() {
  $items['ideas'] = array(
    'page callback' => redhat_ideas_page,
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  
  return $items;
}

function redhat_ideas_page() {
  $content = '<h2>Vote on Features</h2>';
  $content .= views_embed_view('Ideas', 'block_1');
  $content .= '<br />';
  $content .= views_embed_view('Ideas', 'block_2');
  return $content;
}

function vud_views_query_alter(&$view, &$query) {
    if($view->name == 'Ideas'){
        $query->fields['votingapi_cache_node_points_vote_sum_value']['table'] = 'IFNULL(votingapi_cache_node_points_vote_sum';
        $query->fields['votingapi_cache_node_points_vote_sum_value']['field'] = 'value, 0)';
    }
}
