source 'http://rubygems.org'

gem 'rails', '~> 3.2.8'
gem 'recaptcha', :require => 'recaptcha/rails'
gem 'haml', '~> 3.1.2'
#gem 'compass'
gem 'formtastic', '~> 1.2.3'
#gem 'rack'
#gem 'regin'
gem 'rdiscount', '~> 1.6.3'
gem 'httparty'
gem 'wddx'
gem 'crack'
gem 'openshift-origin-console', :require => 'console', :path => ENV['CONSOLE_PATH']

# Files for Barista (https://github.com/Sutto/barista)
#gem 'barista'

gem 'net-http-persistent'

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
# gem 'ruby-debug19', :require => 'ruby-debug'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
group :development, :test do
  # The require part from http://tinyurl.com/3pf68ho
  gem 'mocha', '~> 0.9.8', :require => nil
#  gem 'hpricot'
  gem 'webmock', '~> 1.6.4', :require => nil
#  gem 'rcov', :require => nil if RUBY_VERSION.to_f == 1.8
  gem 'simplecov', :require => nil if RUBY_VERSION.to_f >= 1.9
  gem 'ci_reporter', '~> 1.7.0', :require => nil
  gem 'test-unit' if RUBY_VERSION.to_f >= 1.9
end

group :assets do
  gem 'compass-rails', '~> 1.0.3'
  gem 'sass-rails',    '~> 3.2.5'
  gem 'coffee-rails',  '~> 3.2.2'
  gem 'jquery-rails',  '~> 2.0.2'
  gem 'uglifier',      '>= 1.2.6'
end

gem 'sinatra', '~> 1.2.6'
gem 'sqlite3', '~> 1.3.3'
