source 'http://rubygems.org'

gem 'openshift-origin-console', :require => 'console', :path => ENV['CONSOLE_PATH']

gem 'rack-recaptcha', :require => 'rack/recaptcha'
gem 'rack-picatcha', :require => 'rack/picatcha'

gem 'httparty'
gem 'wddx', '~> 0.4.1'

gem 'sinatra', '~> 1.3.2'
gem 'sqlite3', '~> 1.3.3'
gem 'dalli'

gem 'countries'

# Do not include these gems while testing or compiling assets
group :development, :production do
  gem 'pry' if ENV['PRY']

  if ENV['BETTER_ERRORS']
    gem 'pry-rails' if ENV['PRY']
    gem 'better_errors'
    gem 'binding_of_caller'
    gem 'meta_request'
  end
end

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
group :test, :development do
  gem 'ci_reporter',   '~> 1.7.0', :require => nil
  gem 'test-unit'      if RUBY_VERSION.to_f >= 1.9
  gem 'mocha',         '~> 0.12.1'
  gem 'simplecov',     '~> 0.6.4', :require => nil if RUBY_VERSION.to_f >= 1.9
  gem 'webmock',       '~> 1.6.4'
  gem 'konacha',       '~> 2.5.1'
  gem 'poltergeist',   '~> 1.1.0'

  # Note this is just to get the Konacha CI reporter
  gem 'rspec',         '~> 2.12.0'
end

group :assets do
  gem 'compass-rails', '~> 1.0.3'
  gem 'sass-rails',    '~> 3.2.5'
  gem 'coffee-rails',  '~> 3.2.2'
  gem 'jquery-rails',  '~> 2.0.2'
  gem 'angular-rails', '~> 0.0.12'
  gem 'uglifier',      '>= 1.2.6'
  gem 'therubyracer',  '>= 0.10'
end
