source 'http://rubygems.org'

gem 'openshift-origin-console', :require => 'console', :path => ENV['CONSOLE_PATH']

gem 'rake', '~> 0.9.2'

gem 'rack-recaptcha', :require => 'rack/recaptcha'
gem 'rack-picatcha', :require => 'rack/picatcha'

gem 'httparty'
gem 'wddx', '~> 0.4.1'

gem 'sinatra', '~> 1.3.2'
gem 'sqlite3', '~> 1.3.3'
gem 'dalli'

gem 'countries'

gem 'valvat'

gem 'pry' if ENV['PRY']

gem 'newrelic_rpm', :require => false if File.exists? '/etc/openshift/newrelic.yml'

# Do not include these gems while testing or compiling assets
if ENV['BETTER_ERRORS']
  group :development do
    gem 'pry-rails' if ENV['PRY']
    gem 'better_errors'
    gem 'binding_of_caller'
    gem 'meta_request'
  end
end

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
group :test do
  gem 'ci_reporter',   '~> 1.7.0', :require => false
  gem 'minitest',      '~> 3.5.0', :require => false
  gem 'mocha',         '~> 0.13.3', :require => false
  gem 'simplecov',     '~> 0.6.4', :require => false
  gem 'webmock',       '~> 1.8.0', :require => false
  gem 'poltergeist',   '~> 1.2.0', :require => false
  gem 'capybara',      '~> 2.1.0', :require => false
  gem 'simplecov',     '~> 0.6.4', :require => false 

  # Note:  Only for CI output
  gem 'rspec-core',    '~> 2.8', :require => false
end

group :test, :development do
  gem 'konacha',       '~> 2.6.0'
end

group :assets do
  gem 'compass-rails', '~> 1.0.3'
  gem 'sass-rails',    '~> 3.2.5'
  gem 'coffee-rails',  '~> 3.2.2'
  gem 'jquery-rails',  '~> 2.0.2'
  gem 'angular-rails', '~> 0.0.12'
  gem 'uglifier',      '>= 1.2.6'
  gem 'therubyracer',  '>= 0.10'
  gem 'sass-twitter-bootstrap',  '2.0.1'
end
