#!/bin/bash

# Copyright © 2010 Mike McGrath All rights reserved
# Copyright © 2010 Red Hat, Inc. All rights reserved

# This copyrighted material is made available to anyone wishing to use, modify,
# copy, or redistribute it subject to the terms and conditions of the GNU
# General Public License v.2.  This program is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY expressed or implied, including the
# implied warranties of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.  You should have
# received a copy of the GNU General Public License along with this program;
# if not, write to the Free Software Foundation, Inc., 51 Franklin Street,
# Fifth Floor, Boston, MA 02110-1301, USA. Any Red Hat trademarks that are
# incorporated in the source code or documentation are not subject to the GNU
# General Public License and may only be used or replicated with the express
# permission of Red Hat, Inc.

# Give status of application

# Exit on any errors
set -e

if [ -f '/etc/libra/node.conf' ]
then
    . /etc/libra/node.conf
elif [ -f 'node.conf' ]
then
    . node.conf
else
    echo "node.conf not found.  Cannot continue" 1>&2
    exit 3
fi

CART_DIR=${CART_DIR:=/usr/libexec/li/cartridges}
CART_INFO_DIR=$CART_DIR/embedded/jenkins-client-1.4/info

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Get application status"

    echo "$0 $@" | logger -p local0.notice -t libra_jenkins_status
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

uuid=`basename $3`
application="$1"

APP_HOME="$libra_dir/$uuid/"
APP_DIR="$APP_HOME/$application"

if [ ! -d "$APP_DIR" ]
then
  exit 125
fi

uid=$(id -u "$uuid")
mcs_level=`${CART_DIR}/li-controller/info/bin/mcs_level $uid`

. $APP_HOME/.env/OPENSHIFT_HOMEDIR
. $APP_HOME/.env/OPENSHIFT_APP_NAME
. $APP_HOME/.env/JENKINS_URL
. $APP_HOME/.env/JENKINS_USERNAME

#
# Check application status
#

if false
then
  if [ -n "$JENKINS_URL" ]
  then
      if out=$(runuser --shell /bin/sh "$uuid" -c "runcon -t libra_t -l $mcs_level ${CART_INFO_DIR}/bin/jenkins-cli list-changes -format PLAIN --username "$JENKINS_USERNAME" --password-file "${OPENSHIFT_HOMEDIR}jenkins-client-1.4/.password" '${OPENSHIFT_APP_NAME}-build' 1" 2>&1)
      then
          echo "Latest changes: "
          echo ""
          echo "$out"
      else
          # An error occurred enabling existing job
          echo ""
          echo "Could not get status of job '${OPENSHIFT_APP_NAME}-build' in Jenkins server:"
          echo "$out"
          echo "This might be expected if '${OPENSHIFT_APP_NAME}' isn't running."
      fi
  else
      echo "No Jenkins server found!"
  fi
else
    echo "Coming soon..."
fi    
  