#!/bin/bash

# Give status of application

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Get application status"

    echo "$0 $@" | logger -p local0.notice -t libra_jenkins_status
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

CART_DIR=/usr/libexec/li/cartridges
CART_INFO_DIR=$CART_DIR/embedded/jenkins-client-1.4/info
source ${CART_DIR}/abstract/info/lib/util

setup_basic_hook "$1" $2 $3

. $APP_HOME/.env/OPENSHIFT_HOMEDIR
. $APP_HOME/.env/OPENSHIFT_APP_NAME
. $APP_HOME/.env/JENKINS_URL
. $APP_HOME/.env/JENKINS_USERNAME

#
# Check application status
#

echo "You can see the job status here:"
echo "${JENKINS_URL}job/${OPENSHIFT_APP_NAME}-build/"    
  
