#!/bin/bash

# Start the application httpd instance

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Start a running application"

    echo "$0 $@" | logger -p local0.notice -t libra_httpd_start
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

CART_DIR=/usr/libexec/li/cartridges
source ${CART_DIR}/abstract/info/lib/util

setup_configure "$1" $2 $3

import_env_vars

rm -f $APP_HOME/.env/OPENSHIFT_CACHE_PROXY_PORT
proxy_port=$(remove_proxy_port $uuid "$OPENSHIFT_CACHE_HOST:$OPENSHIFT_CACHE_PORT")
ret=$?
if [ $ret -ne 0 ]; then
  client_error "$proxy_port"
  exit $ret
fi
exit 0
