#!/bin/bash

# Control application's embedded Memcached server instance
CART_NAME=memcached
CART_VERSION=1.4
CART_DIRNAME=${CART_NAME}-$CART_VERSION
CART_DIR=${CART_DIR:=/usr/libexec/li/cartridges}


# Exit on any errors
set -e


function print_help() {
    cmd=$(basename "$0")
    echo "Usage: $0 app-name namespace uuid"
    echo "$cmd embedded Memcached service"

    echo "$0 $@" | logger -p local0.notice -t libra_memcached_$cmd
    exit 1

}  #  End of function  print_help.


function _control_memcached_service() {
   [ $# -lt 1 ]  &&  return 1
   ctl_cmd="runcon -t libra_t -l $mcs_level $CTL_SCRIPT $1"
   /bin/su -s /bin/sh "$uuid" -c "$ctl_cmd"

}  #  End of function  _control_memcached_service.


function _start_memcached_service() {
   rm -f "$CART_INSTANCE_DIR/run/stop_lock"
   _control_memcached_service "start"

}  #  End of function  _start_memcached_service.


function _stop_memcached_service() {
   _control_memcached_service "stop"
   touch "$CART_INSTANCE_DIR/run/stop_lock"

}  #  End of function  _stop_memcached_service.


function _restart_memcached_service() {
   rm -f "$CART_INSTANCE_DIR/run/stop_lock"
   _control_memcached_service "restart"

}  #  End of function  _restart_memcached_service.


function _reload_memcached_service() {
   :  #  Do nothing.
}  #  End of function  _reload_memcached_service.


function _move_memcached_service() {
   source ${CART_DIR}/abstract/info/lib/selinux
   source ${CART_DIR}/abstract/info/lib/apache
   source ${CART_DIR}/abstract/info/lib/network
   load_node_conf

MEMCACHED_DIR="$APP_HOME/memcached-1.4/"   

. $APP_HOME/.env/OPENSHIFT_INTERNAL_IP
IP=$OPENSHIFT_INTERNAL_IP

. $APP_HOME/.env/OPENSHIFT_CACHE_PORT
. $APP_HOME/.env/OPENSHIFT_CACHE_HOST

ORIG_DB_HOST=$OPENSHIFT_CACHE_HOST
echo "export OPENSHIFT_CACHE_URL='memcached://$IP:$OPENSHIFT_CACHE_PORT/'" > $APP_HOME/.env/OPENSHIFT_CACHE_URL

set_app_info "Connection URL: memcached://$IP:$OPENSHIFT_CACHE_PORT/"

}  #  End of function  _move_memcached_service.

function _pre_move_memcached_service() {
   source ${CART_DIR}/abstract/info/lib/selinux
   source ${CART_DIR}/abstract/info/lib/apache
   source ${CART_DIR}/abstract/info/lib/network
   load_node_conf

}  #  End of function  _pre_move_memcached_service.

function _post_move_memcached_service() {
   source ${CART_DIR}/abstract/info/lib/selinux
   source ${CART_DIR}/abstract/info/lib/apache
   source ${CART_DIR}/abstract/info/lib/network
   load_node_conf

}  #  End of function  _post_move_memcached_service.



#
# main():
#
source ${CART_DIR}/abstract/info/lib/util

# Parse and ensure arguments.
while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x ;;
        ?) print_help ;;
    esac
done

[ $# -eq 3 ] || print_help
setup_basic_hook "$1" $2 $3

# Setup instance directory and control script name.
CART_INSTANCE_DIR="$APP_HOME/$CART_DIRNAME"
CTL_SCRIPT="$CART_INSTANCE_DIR/${application}_${CART_NAME}_ctl.sh"

cmd=$(basename "$0")
case "$cmd" in
   status)    runuser --shell /bin/sh "$uuid" "$CTL_SCRIPT" status ;;
   start)     _start_memcached_service     ;;
   stop)      _stop_memcached_service      ;;
   restart)   _restart_memcached_service   ;;
   reload)    _reload_memcached_service    ;;
   move)      _move_memcached_service      ;;
   pre-move)  _pre_move_memcached_service  ;;
   post-move) _post_move_memcached_service ;;
esac

