#!/bin/bash

# Destroys Memcached instance

function print_help {
    echo "Usage: $0 app-name namespace uuid"

    echo "$0 $@" | logger -p local0.notice -t libra_memcached_deconfigure
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

CART_DIR=${CART_DIR:=/usr/libexec/li/cartridges}
source ${CART_DIR}/abstract/info/lib/util

app_type="memcached-1.4"
setup_embedded_deconfigure "$1" $2 $3

source ${CART_INFO_DIR}/lib/util

MEMCACHED_DIR="$APP_HOME/memcached-1.4/"

#
# Teardown port proxy (ignore failures or missing hook)
#
( ${CART_INFO_DIR}/hooks/conceal-port "$1" $2 $3 ) &>/dev/null || :

#
# Remove environment variables
#
[ -f $APP_HOME/.env/OPENSHIFT_CACHE_TYPE ]  &&  source $APP_HOME/.env/OPENSHIFT_CACHE_TYPE

if [ "$OPENSHIFT_CACHE_TYPE" = "memcached" ]; then
   /bin/rm -f $APP_HOME/.env/OPENSHIFT_CACHE $APP_HOME/.env/OPENSHIFT_CACHE_HOST $APP_HOME/.env/OPENSHIFT_CACHE_PORT $APP_HOME/.env/OPENSHIFT_CACHE_SOCKET $APP_HOME/.env/OPENSHIFT_CACHE_URL $APP_HOME/.env/OPENSHIFT_CACHE_CTL_SCRIPT
fi

stop_memcached

confirm_pid_gone "${MEMCACHED_DIR}/pid/memcached.pid"

runcon -l s0-s0:c0.c1023 rm -rf "$MEMCACHED_DIR" "$MEMCACHED_DIR/${application}_memcached_ctl.sh"

