source 'https://rubygems.org'

gem 'rails', '~> 3.2.8'

gem 'json'
gem 'parseconfig'

gem 'openshift-origin-controller'

group :development do
  gem 'minitest'
  gem 'simplecov'
  gem 'mocha'
end

#gem 'mongoid'

gem 'xml-simple'
gem 'regin'

gem 'mongo_mapper'
gem 'wddx'
gem 'pony'
gem 'systemu'
gem 'rest-client'

gem 'openshift-origin-dns-dynect'
gem 'openshift-origin-auth-streamline'

gem 'openshift-origin-msg-broker-mcollective', :require => "openshift-origin-msg-broker-mcollective"
