source 'https://rubygems.org'

gem 'rails', '~> 3.2.8'

gem 'json'
gem 'parseconfig'
gem 'bson'
gem 'bson_ext'
gem 'uuidtools'

gem 'openshift-origin-controller'

group :other do
  gem 'minitest', '~> 3.5.0'
  gem 'simplecov'
  gem 'mocha',    '~> 0.13.3'
end

gem 'mongoid'

gem 'xml-simple'
gem 'regin'

gem 'mongo_mapper'
gem 'wddx'
gem 'pony'
gem 'systemu'
gem 'rest-client'
gem 'dalli'

gem 'openshift-origin-dns-dynect'
gem 'openshift-origin-billing-aria'
gem 'openshift-origin-auth-streamline'

gem 'openshift-origin-msg-broker-mcollective', :require => "openshift-origin-msg-broker-mcollective"
if File.exists? '/etc/openshift/plugins.d/openshift-origin-admin-console.conf'
  gem 'openshift-origin-admin-console'
  gem 'sass-twitter-bootstrap', '2.0.1'
  gem 'compass-rails', '~> 1.0.3'
  gem 'sass-rails',    '~> 3.2.5'
  gem 'coffee-rails',  '~> 3.2.2'
  gem 'jquery-rails',  '~> 2.0.2'
  gem 'uglifier',      '>= 1.2.6'
  gem 'therubyracer',  '>= 0.10'
end
