source 'https://rubygems.org'

gem 'rails', '~> 3.2.8'

gem 'json'
gem 'parseconfig'
gem 'bson'
gem 'bson_ext'
gem 'uuidtools'

gem 'openshift-origin-controller'

group :other do
  gem 'minitest', '~> 3.5.0'
  gem 'simplecov'
  gem 'mocha',    '~> 0.13.3'
end

gem 'mongoid'

gem 'xml-simple'
gem 'regin'

gem 'mongo_mapper'
gem 'wddx'
gem 'pony'
gem 'systemu'
gem 'rest-client'
gem 'dalli'

gem 'openshift-origin-dns-dynect'
gem 'openshift-origin-billing-aria'
gem 'openshift-origin-auth-streamline'

gem 'openshift-origin-msg-broker-mcollective', :require => "openshift-origin-msg-broker-mcollective"
gem 'openshift-origin-admin-console' if File.exists? '/etc/openshift/plugins.d/openshift-origin-admin-console.conf'
