<?php

function redhat_frontpage_menu() {

  $not_found = array(
    'page callback' => redhat_not_found,
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'title' => 'Page not found',
  );
  $items['_errors/404'] = $not_found;
  
  $access_denied = array(
    'page callback' => redhat_access_denied,
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'title' => 'Access denied',
  );
  $items['_errors/403'] = $access_denied;

  $item = array(
    'page callback' => redhat_frontpage,
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'title' => "Welcome to OpenShift",
  );
  $items['<front>'] = $item;
  $items['home'] = $item;
  return $items;
}

function redhat_not_found() {
  $content = ' <section class="row">
                  <div class="span12">
                    <h2>The page you requested may no longer exist</h2>
                    <form class="form-search">
                      <input class="search">
                      <input class="btn btn-primary" value="Search" type="button">
                    </form>
                    <p><a href="/">Return to our homepage.</a></p>
                    <p><a href="mailto:openshift@redhat.com">Contact us</a> if you feel you have reached this page in error.</p>
                  </div>
                  </section>';
  return $content;
}

function redhat_access_denied() {
  $content = ' <section class="row">
                  <div class="span12">
                    <h2>You do not have permission to access this page</h2>
                    <p><a href="/">Return to our homepage.</a></p>
                    <p><a href="mailto:openshift@redhat.com">Contact us</a> if you feel you have reached this page in error.</p>
                  </div>
                  </section>';
  return $content;
}


function redhat_frontpage(){
  global $user;
  $content = '';

  $view = views_get_view('forum_views');
  $args[] = $user->uid;
  $view->execute_display('block_1', $args);
  $num_rows = count($view->result);


  if ($user->uid) {
    $content .= "Welcome to the OpenShift Community pages!<br />
                 This is the place to learn and engage with other OpenShift users and developers.<br />";
  } else {
    $content .= "Join the OpenShift Community! Sign In to participate. <br />
                 This is the place to learn and engage with OpenShift users and developers. <br />";
  } 

  if ($num_rows > 0) {
    $content .= "<br /><h3>My Threads</h3>";
    $content .= views_embed_view('forum_views', 'block_1', $user->uid);
  }
  else { 
    $content .= "<br /><h3>Recent Threads</h3>";
    $content .= views_embed_view('threads_by_popularity', 'block_6');
  }
  $content .= "<h3>Recent Blog Posts</h3>";
  $content .= views_embed_view('nodes_by_category', 'block_1');
  $content .= "<br /><h3>Upcoming Events</h3>";
  $content .= views_embed_view('event_view', 'block_3');
  $content .= "<br /><h3>Popular FAQs</h3>";
  $content .= views_embed_view('faq_frontpage');

  return $content;
}
