<?php

function redhat_frontpage_menu() {

  $not_found = array(
    'page callback' => redhat_page_not_found,
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'title' => 'Page not found',
  );
  $items['_errors/404'] = $not_found;
  
  $access_denied = array(
    'page callback' => redhat_page_access_denied,
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'title' => 'Access denied',
  );
  $items['_errors/403'] = $access_denied;

  $item = array(
    'page callback' => redhat_page_home,
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'title' => "OpenShift by Red Hat",
  );
  $items['<front>'] = $item;
  $items['home'] = $item;

  $items['community'] = array(
    'page callback' => redhat_page_community,
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'title' => "Community",
    'menu_name' => 'primary-links',
  );
  return $items;
}

function redhat_page_not_found() {
  $content = ' <section class="row">
                  <div class="span12">
                    <h2>The page you requested may no longer exist</h2>
                    <form class="form-search" action="'.url('search').'" method="get">
                      <input class="search" name="keys">
                      <input class="btn btn-primary" value="Search" type="button">
                    </form>
                    <p><a href="/">Return to our homepage.</a></p>
                    <p><a href="mailto:openshift@redhat.com">Contact us</a> if you feel you have reached this page in error.</p>
                  </div>
                  </section>';
  return $content;
}

function redhat_page_access_denied() {
  global $user;
  if (user_is_anonymous()) {
    header('Location: ' . url('user', array('query' => drupal_get_destination(), 'absolute' => TRUE)), TRUE, 302);
    drupal_exit();
    #drupal_goto('user', drupal_get_destination());
  }
  $content = ' <section class="row">
                  <div class="span12">
                    <h2>You do not have permission to access this page</h2>
                    <p><a href="/">Return to our homepage.</a></p>
                    <p><a href="mailto:openshift@redhat.com">Contact us</a> if you feel you have reached this page in error.</p>
                  </div>
                  </section>';
  return $content;
}

function redhat_page_home() {
  $content = ' <section class="row">
                  <div class="span12">
                    <h2>I\'m a homepage</h2>
                  </div>
                  </section>';
  return $content;
}

function redhat_page_community(){
  global $user;
  $content = '';

  $view = views_get_view('forum_views');
  $args[] = $user->uid;
  $view->execute_display('block_1', $args);
  $num_rows = count($view->result);


  if ($user->uid) {
    $content .= "Welcome to the OpenShift Community! This is the place to learn and engage with other OpenShift users and developers.<br />";
  } else {
    $content .= "<a href=\"/user\">Sign in</a> or <a href=\"";
    $content .= redhat_sso_register_url();
    $content .= "\">sign up</a> to participate in the community. This is the place to learn and engage with OpenShift users and developers. <br />";
  } 

  if ($user->uid && $num_rows > 0) {
    $content .= "<br /><h3>My Threads</h3>";
    $content .= views_embed_view('forum_views', 'block_1', $user->uid);
  }
  else {
    $content .= "<br /><h3>Recent Threads</h3>";
    $content .= views_embed_view('threads_by_popularity', 'block_6');
  }
  $content .= "<h3>Recent Blog Posts</h3>";
  $content .= views_embed_view('nodes_by_category', 'block_1');
  $content .= "<br /><h3>Upcoming Events</h3>";
  $content .= views_embed_view('event_view', 'block_3');
  $content .= "<br /><h3>Popular FAQs</h3>";
  $content .= views_embed_view('faq_frontpage');

  return $content;
}

function _redhat_frontpage_load_tweets() {
  return _redhat_frontpage_cache_request('/app/twitter/latest_tweets');
}

function _redhat_frontpage_load_retweets() {
  return _redhat_frontpage_cache_request('/app/twitter/latest_retweets');
}

function _redhat_frontpage_cache_request($url) {
  $response = cache_get($url);
  if ($response == 0) {
    $response = "";
    try {
      $request_url = openshift_server_url() . $url;
      $response = drupal_http_request($request_url, array(), 'GET', NULL, 0, 5.0);
      if ($response->code == 200) {
        $response = filter_xss($response->data, array('a','img','div','p','small','cite','code','em','span'));
        cache_set($url, $response, 'cache', $_SERVER['REQUEST_TIME'] + 60*60*1);
      }
    } catch (Exception $e) {
    }
  } else {
    $response = $response->data;
  }
  return $response;
}
