<?php

function redhat_frontpage_install() {
  db_query("UPDATE {system} SET weight = 50 where type = 'module' and name = 'redhat_frontpage'");
}

function redhat_frontpage_menu() {

  $not_found = array(
    'page callback' => redhat_page_not_found,
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'title' => 'Page not found',
  );
  $items['_errors/404'] = $not_found;
  
  $access_denied = array(
    'page callback' => redhat_page_access_denied,
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'title' => 'Access denied',
  );
  $items['_errors/403'] = $access_denied;

  $item = array(
    'page callback' => redhat_page_home,
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['<front>'] = $item;
  $items['home'] = $item;

  $items['community'] = array(
    'page callback' => redhat_page_community,
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'title' => "Community",
    'menu_name' => 'primary-links',
  );
  return $items;
}

function redhat_frontpage_form_menu_configure_alter(&$form, &$form_state) {
  $form['reset_primary_nav_fieldset'] = array(
    '#type' => 'fieldset',
    '#title' => t('Reset primary link blocks'),
    '#collapsible' => FALSE,
    '#collapsed' => FALSE, 
  );
  $form['reset_primary_nav_fieldset']['reset_primary_nav'] = array (
    '#type' => 'submit',
    '#value' => 'Reset',
    '#submit' => array('redhat_reset_nav_map'),
    '#prefix'=> '<div class="description">Reset the cached map of the primary link megamenu custom blocks.  Megamenu custom blocks have titles that match the pattern megamenu_custom_/path where /path is the external href of the primary link.</div>'
  );
}

function redhat_frontpage_form_search_form_alter(&$form, &$form_state) {
  # we don't need CSRF checking for the search form, remove it to allow for cached views
  # with embedded search forms
  unset($form['#token']);
}

/**
 * Implementation of hook_context_page_condition().
 */
function redhat_frontpage_context_page_condition() {
  $map = context_condition_map();
  #watchdog('redhat_frontpage', '=== Init ===');
  if (!empty($map['context_active']) && $plugin = context_get_plugin('condition', 'context_active')) {
    $plugin->execute();
  }
}

/**
 * Implementation of hook_context_plugins().
 */
function redhat_frontpage_context_plugins() {
  $plugins = array();
  $plugins['context_condition_context_active'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'redhat_frontpage') . '/plugins',
      'file' => 'context_condition_context_active.inc',
      'class' => 'context_condition_context_active',
      'parent' => 'context_condition',
    ),
  );
  return $plugins;
}

/**
 * Implementation of hook_context_registry().
 */
function redhat_frontpage_context_registry() {
  return array(
    'conditions' => array(
      'context_active' => array(
        'title' => t('Active Context'),
        'description' => t('Activate this context only if other contexts are live or not'),
        'plugin' => 'context_condition_context_active',
      ),
    ),
  );
}


function redhat_page_not_found() {
  $content = ' <section class="row">
                  <div class="span12">
                    <h2>The page you requested may no longer exist</h2>
                    <form class="form-search" action="'.url('search').'" method="get">
                      <input class="search" name="keys">
                      <input class="btn btn-primary" value="Search" type="button">
                    </form>
                    <p><a href="/">Return to our homepage.</a></p>
                    <p><a href="mailto:openshift@redhat.com">Contact us</a> if you feel you have reached this page in error.</p>
                  </div>
                  </section>';
  return $content;
}

function redhat_page_access_denied() {
  global $user;
  if (user_is_anonymous()) {
    header('Location: ' . url('user', array('query' => drupal_get_destination(), 'absolute' => TRUE)), TRUE, 302);
    exit;
    #drupal_goto('user', drupal_get_destination());
  }
  $content = ' <section class="row">
                  <div class="span12">
                    <h2>You do not have permission to access this page</h2>
                    <p><a href="/">Return to our homepage.</a></p>
                    <p><a href="mailto:openshift@redhat.com">Contact us</a> if you feel you have reached this page in error.</p>
                  </div>
                  </section>';
  return $content;
}

function redhat_page_home() {
  $content = ' <section class="row">
                  <div class="span12">
                    <h2>I\'m a homepage</h2>
                  </div>
                  </section>';
  return $content;
}

function redhat_page_community(){
  global $user;
  $content = '';

  $view = views_get_view('forum_views');
  $args[] = $user->uid;
  $view->execute_display('block_1', $args);
  $num_rows = count($view->result);


  if ($user->uid) {
    $content .= "Welcome to the OpenShift Community! This is the place to learn and engage with other OpenShift users and developers.<br />";
  } else {
    $content .= "<a href=\"/user\">Sign in</a> or <a href=\"";
    $content .= redhat_sso_register_url();
    $content .= "\">sign up</a> to participate in the community. This is the place to learn and engage with OpenShift users and developers. <br />";
  } 

  if ($user->uid && $num_rows > 0) {
    $content .= "<br /><h3>My Threads</h3>";
    $content .= views_embed_view('forum_views', 'block_1', $user->uid);
  }
  else {
    $content .= "<br /><h3>Recent Threads</h3>";
    $content .= views_embed_view('threads_by_popularity', 'block_6');
  }
  $content .= "<h3>Recent Blog Posts</h3>";
  $content .= views_embed_view('nodes_by_category', 'block_1');
  $content .= "<br /><h3>Upcoming Events</h3>";
  $content .= views_embed_view('event_view', 'block_3');
  $content .= "<br /><h3>Popular FAQs</h3>";
  $content .= views_embed_view('faq_frontpage');

  return $content;
}

function redhat_reset_nav_map($form, &$form_state) {
  $menuMap = array();
  $result = db_query("SELECT bid, info FROM {boxes} WHERE info LIKE '%s%'", "megamenu_custom_");
  if ($result) {
    while($row = db_fetch_array($result)) {
      $info = $row['info'];
      $path = substr($info, 16);
      $menuMap[$path] = $row['bid'];
    }
  }
  variable_set("megamenu_custom_blocks", $menuMap);
  drupal_goto("admin/build/menu/settings");
}

function _redhat_frontpage_load_tweets() {
  return _redhat_frontpage_cache_request('/app/twitter/latest_tweets');
}

function _redhat_frontpage_load_retweets() {
  return _redhat_frontpage_cache_request('/app/twitter/latest_retweets');
}

function _redhat_frontpage_cache_request($url) {
  $response = cache_get($url);
  if ($response == 0) {
    $response = "";
    try {
      $request_url = openshift_server_url() . $url;
      $response = drupal_http_request($request_url, array(), 'GET', NULL, 0, 5.0);
      if ($response->code == 200) {
        $response = filter_xss($response->data, array('a','img','div','p','small','cite','code','em','span'));
        cache_set($url, $response, 'cache', $_SERVER['REQUEST_TIME'] + 60*60*1);
      }
    } catch (Exception $e) {
    }
  } else {
    $response = $response->data;
  }
  return $response;
}
