#!/bin/bash

# Copyright © 2010 Mike McGrath All rights reserved
# Copyright © 2010 Red Hat, Inc. All rights reserved

# This copyrighted material is made available to anyone wishing to use, modify,
# copy, or redistribute it subject to the terms and conditions of the GNU
# General Public License v.2.  This program is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY expressed or implied, including the
# implied warranties of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.  You should have
# received a copy of the GNU General Public License along with this program;
# if not, write to the Free Software Foundation, Inc., 51 Franklin Street,
# Fifth Floor, Boston, MA 02110-1301, USA. Any Red Hat trademarks that are
# incorporated in the source code or documentation are not subject to the GNU
# General Public License and may only be used or replicated with the express
# permission of Red Hat, Inc.

# Move to a new ip

# Exit on any errors
set -e

CART_DIR=/usr/libexec/li/cartridges

source ${CART_DIR}/abstract/info/lib/util
source ${CART_DIR}/abstract/info/lib/selinux
source ${CART_DIR}/abstract/info/lib/apache
source ${CART_DIR}/abstract/info/lib/network

load_node_conf

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done

[ $# -eq 3 ] || print_help

namespace=`basename $2`
application="$1"
uuid=$3

setup_basic_vars

CART_INFO_DIR=$CART_DIR/embedded/mongodb-2.0/info
source ${CART_INFO_DIR}/lib/util

MONGODB_DIR="$APP_HOME/mongodb-2.0/"

. $APP_HOME/.env/OPENSHIFT_NOSQL_DB_HOST
ORIG_DB_HOST=$OPENSHIFT_NOSQL_DB_HOST

. $APP_HOME/.env/OPENSHIFT_INTERNAL_IP
IP=$OPENSHIFT_INTERNAL_IP

. $APP_HOME/.env/OPENSHIFT_NOSQL_DB_PASSWORD
. $APP_HOME/.env/OPENSHIFT_NOSQL_DB_USERNAME

echo "export OPENSHIFT_NOSQL_DB_HOST='$IP'" > $APP_HOME/.env/OPENSHIFT_NOSQL_DB_HOST
echo "export OPENSHIFT_NOSQL_DB_URL='mongodb://$OPENSHIFT_NOSQL_DB_USERNAME:$OPENSHIFT_NOSQL_DB_PASSWORD@$IP:27017/'" > $APP_HOME/.env/OPENSHIFT_NOSQL_DB_URL

sed -i "s,$ORIG_DB_HOST,$IP," $MONGODB_DIR/etc/mongodb.conf

set_app_info "Connection URL: mongodb://$IP:27017/"
