#!/bin/bash

# Restarts instance

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Get application status"

    echo "$0 $@" | logger -p local0.notice -t libra_mysql_restart
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

CART_DIR=/usr/libexec/li/cartridges
source ${CART_DIR}/abstract/info/lib/util

setup_basic_hook "$1" $2 $3

MONGODB_DIR="$APP_HOME/mongodb-2.0/"
mongodbctl="$MONGODB_DIR/${application}_mongodb_ctl.sh"


#
# Restart application
#
rm -f "$MONGODB_DIR/run/stop_lock"
super_run_as_user "$mongodbctl restart"
