#!/bin/bash

# Destroys phpmoadmin instance

function print_help {
    echo "Usage: $0 app-name namespace uuid"

    echo "$0 $@" | logger -p local0.notice -t stickshift_phpmoadmin_deconfigure
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done

[ $# -eq 3 ] || print_help

cartridge_type="phpmoadmin-1.0"
source "/etc/stickshift/stickshift-node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_embedded_deconfigure "$1" $2 $3

PHPMOADMIN_DIR=$(get_cartridge_instance_dir "$cartridge_type")
PHPMOADMIN_CTL_SCRIPT="$PHPMOADMIN_DIR/${application}_phpmoadmin_ctl.sh"

#
# Stop app
#
run_as_user "$PHPMOADMIN_CTL_SCRIPT stop" || warning "Failed to stop ${application}" 121

confirm_pid_gone "${PHPMOADMIN_DIR}/run/httpd.pid"

confirm_log_files_inactive "$PHPMOADMIN_DIR/logs"

#
# Remove environment variables
#
/bin/rm -f $APP_HOME/.env/OPENSHIFT_PHPMOADMIN_GEAR_DIR $APP_HOME/.env/OPENSHIFT_PHPMOADMIN_CTL_SCRIPT $APP_HOME/.env/OPENSHIFT_PHPMOADMIN_IP $APP_HOME/.env/OPENSHIFT_PHPMOADMIN_USERNAME $APP_HOME/.env/OPENSHIFT_PHPMOADMIN_PASSWORD


# Remove phpmoadmin dir. This MUST be after stopping phpmoadmin as the CTL script relies on these.
runcon -l s0-s0:c0.c1023 rm -rf "$PHPMOADMIN_DIR"

#
# Remove ProxyPass definition from apache
#
rm -f /etc/httpd/conf.d/stickshift/${uuid}_${namespace}_${application}/phpmoadmin-1.0.conf || warning "Could not remove phpmoadmin apache definition" 156

${CARTRIDGE_BASE_PATH}/abstract/info/bin/httpd_singular graceful || warning "Failed to restart master httpd, please contact support" 120
