#!/bin/bash

# Destroys phpmoadmin instance

function print_help {
    echo "Usage: $0 app-name namespace uuid"

    echo "$0 $@" | logger -p local0.notice -t stickshift_phpmoadmin_deconfigure
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done

[ $# -eq 3 ] || print_help

source "/etc/stickshift/stickshift-node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

# Import Environment Variables
for f in ~/.env/*
do
    . $f
done

cartridge_type="phpmoadmin-1.0"
cartridge_dir=$OPENSHIFT_HOMEDIR/$cartridge_type


setup_embedded_deconfigure "$1" $2 $3


#
# Stop app
#
run_as_user "${CARTRIDGE_BASE_PATH}/${cartridge_type}/info/bin/app_ctl.sh stop" || warning "Failed to stop ${application}" 121

confirm_pid_gone "${cartridge_dir}/run/httpd.pid"

confirm_log_files_inactive "${cartridge_dir}/logs"

#
# Remove environment variables
#
/bin/rm -f $APP_HOME/.env/OPENSHIFT_PHPMOADMIN_IP $APP_HOME/.env/OPENSHIFT_PHPMOADMIN_USERNAME $APP_HOME/.env/OPENSHIFT_PHPMOADMIN_PASSWORD


# Remove phpmoadmin dir. This MUST be after stopping phpmoadmin as the CTL script relies on these.
runcon -l s0-s0:c0.c1023 rm -rf "${cartridge_dir}"

#
# Remove ProxyPass definition from apache
#
rm -f /etc/httpd/conf.d/stickshift/${uuid}_${namespace}_${application}/phpmoadmin-1.0.conf || warning "Could not remove phpmoadmin apache definition" 156

${CARTRIDGE_BASE_PATH}/abstract/info/bin/httpd_singular graceful || warning "Failed to restart master httpd, please contact support" 120
