#!/bin/bash

# Copyright © 2010 Mike McGrath All rights reserved
# Copyright © 2010 Red Hat, Inc. All rights reserved

# This copyrighted material is made available to anyone wishing to use, modify,
# copy, or redistribute it subject to the terms and conditions of the GNU
# General Public License v.2.  This program is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY expressed or implied, including the
# implied warranties of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.  You should have
# received a copy of the GNU General Public License along with this program;
# if not, write to the Free Software Foundation, Inc., 51 Franklin Street,
# Fifth Floor, Boston, MA 02110-1301, USA. Any Red Hat trademarks that are
# incorporated in the source code or documentation are not subject to the GNU
# General Public License and may only be used or replicated with the express
# permission of Red Hat, Inc.

# Deploy httpd proxy

# Exit on any errors
set -e

CART_DIR=/usr/libexec/li/cartridges

source ${CART_DIR}/abstract/info/lib/util
source ${CART_DIR}/abstract/info/lib/selinux
source ${CART_DIR}/abstract/info/lib/apache
source ${CART_DIR}/abstract/info/lib/network

load_node_conf

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done

[ $# -eq 3 ] || print_help

namespace=`basename $2`
application="$1"
uuid=$3

setup_basic_vars

CART_INFO_DIR=$CART_DIR/embedded/phpmoadmin-1.0/info

PHPMOADMIN_IP=`embedded_find_open_ip $uid $APP_HOME`
echo "export OPENSHIFT_PHPMOADMIN_IP='$PHPMOADMIN_IP'" > $APP_HOME/.env/OPENSHIFT_PHPMOADMIN_IP
$CART_INFO_DIR/bin/deploy_httpd_config.sh $application $uuid $PHPMOADMIN_IP
$CART_INFO_DIR/bin/deploy_httpd_proxy.sh $application $namespace $uuid $PHPMOADMIN_IP

restart_httpd_graceful
