#!/bin/bash

# Move to a new ip

# Exit on any errors
set -e

source "/etc/openshift/node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/apache
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/network

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done

[ $# -eq 3 ] || print_help

namespace=`basename $2`
application="$1"
uuid=$3

setup_basic_vars

CART_INFO_DIR=$CARTRIDGE_BASE_PATH/embedded/phpmoadmin-1.0/info

PHPMOADMIN_DIR="$APP_HOME/phpmoadmin-1.0"
observe_setup_var_lib_dir "$PHPMOADMIN_DIR"

PHPMOADMIN_IP=`embedded_find_open_ip $uid $APP_HOME`
echo "export OPENSHIFT_PHPMOADMIN_IP='$PHPMOADMIN_IP'" > $APP_HOME/.env/OPENSHIFT_PHPMOADMIN_IP
$CART_INFO_DIR/bin/deploy_httpd_config.sh $application $uuid $PHPMOADMIN_IP
$CART_INFO_DIR/bin/deploy_httpd_proxy.sh $application $namespace $uuid $PHPMOADMIN_IP

restart_httpd_graceful