#!/bin/bash

# Gets status of instance

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Stop a running application and disable it"

    echo "$0 $@" | logger -p local0.notice -t libra_phpmoadmin_status
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

CART_DIR=/usr/libexec/li/cartridges
source ${CART_DIR}/abstract/info/lib/util

setup_basic_hook "$1" $2 $3

PHPMOADMIN_DIR=`echo $APP_HOME/phpmoadmin-1.0 | tr -s /` # ensure that there aren't double /'s
PHPMOADMIN_CTL_SCRIPT="$PHPMOADMIN_DIR/${application}_phpmoadmin_ctl.sh"


#
# Start application
#
ADDRESS="$(awk '/Listen/{ print $2 }' $PHPMOADMIN_DIR/conf.d/libra.conf)"
URL="http://$ADDRESS/phpmoadmin"

runuser --shell /bin/sh "$uuid" -c "/usr/bin/wget -qO- $URL >> /dev/null ; if [ \$? -ne 0 ]; then echo Stopped; else echo Running; fi"
