#!/bin/bash

# Gets status of instance

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Stop a running application and disable it"

    echo "$0 $@" | logger -p local0.notice -t stickshift_phpmoadmin_status
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

source "/etc/stickshift/stickshift-node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_basic_hook "$1" $2 $3

PHPMOADMIN_DIR=`echo $APP_HOME/phpmoadmin-1.0 | tr -s /` # ensure that there aren't double /'s


#
# Start application
#
ADDRESS="$(awk '/Listen/{ print $2 }' $PHPMOADMIN_DIR/conf.d/stickshift.conf)"
URL="http://$ADDRESS/phpmoadmin"

if output=$(runuser --shell /bin/sh "$uuid" -c "/usr/bin/wget -qO- $URL >> /dev/null ; if [ \$? -ne 0 ]; then echo Stopped; else echo Running; fi" 2>&1)
then
    status_client_result "$output"
else
    client_result "PHPMoAdmin is either stopped or inaccessible"
fi
