#!/bin/bash

# Destroys zend instance

function print_help {
    echo "Usage: $0 app-name namespace uuid"

    echo "$0 $@" | logger -p local0.notice -t stickshift_php_deconfigure
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

source "/etc/stickshift/stickshift-node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_deconfigure "$1" $2 $3

$CART_INFO_DIR/hooks/conceal-port "$application" "$namespace" "$uuid"

destroy_git_repo $application $uuid

stop_app

confirm_pid_gone "${APP_DIR}/run/httpd.pid"

confirm_log_files_inactive "$APP_DIR/logs"

rm_app_dir


#
# Remove virtualhost definition for apache
#
rm_httpd_proxy $uuid $namespace $application
