#!/bin/bash

# Move to a new ip

# Exit on any errors
set -e

source "/etc/stickshift/stickshift-node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/apache
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/network

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done

[ $# -eq 3 ] || [ $# -eq 4 ] || print_help

namespace=`basename $2`
application="$1"
uuid=$3
idle=false
if [ "$4" == "--idle" ]
then
  idle=true
fi

setup_basic_vars

. $APP_HOME/.env/OPENSHIFT_GEAR_TYPE
cartridge_type=$OPENSHIFT_GEAR_TYPE

CART_INFO_DIR=$CARTRIDGE_BASE_PATH/$OPENSHIFT_GEAR_TYPE/info

observe_setup_app_home
observe_setup_app_and_git_dirs
observe_setup_cart_instance_dir

#
# Find an open localhost IP
#
IP=`find_open_ip $uid $uuid`
echo "export OPENSHIFT_INTERNAL_IP='$IP'" > $APP_HOME/.env/OPENSHIFT_INTERNAL_IP
if [ -f $CART_INFO_DIR/bin/deploy_httpd_config.sh ]
then
  $CART_INFO_DIR/bin/deploy_httpd_config.sh $application $uuid $IP
fi

run_as_user "${CARTRIDGE_BASE_PATH}/abstract/info/bin/redeploy_config_dir.sh"

. $APP_HOME/.env/OPENSHIFT_INTERNAL_IP

#copy over zen config files
ZENDCART_INSTANCE_DIR=$(get_cartridge_instance_dir "$cartridge_type")
ZEND_USER_FILES="/usr/libexec/stickshift/cartridges/${cartridge_type}/files/user-files"
$CART_INFO_DIR/bin/zend_configure_filesystem_post_move.sh ${ZEND_USER_FILES} ${ZENDCART_INSTANCE_DIR} ${uid} ${uid} ${OPENSHIFT_INTERNAL_IP} || error "Failed to copy files to cartridge directory" 121

#
# Create virtualhost definition for apache
#
export CART_INFO_DIR
if [ -f $CART_INFO_DIR/bin/deploy_httpd_proxy.sh ]
then
  $CART_INFO_DIR/bin/deploy_httpd_proxy.sh $application $namespace $uuid $OPENSHIFT_INTERNAL_IP
else
  $CARTRIDGE_BASE_PATH/abstract/info/bin/deploy_httpd_proxy.sh $application $namespace $uuid $OPENSHIFT_INTERNAL_IP
fi

if $idle
then
  rhc-idler -u $uuid
fi

restart_httpd_graceful
