#!/bin/bash

# Copyright © 2010 Mike McGrath All rights reserved
# Copyright © 2011 Scott Stark All rights reserved
# Copyright © 2010 Red Hat, Inc. All rights reserved

# This copyrighted material is made available to anyone wishing to use, modify,
# copy, or redistribute it subject to the terms and conditions of the GNU
# General Public License v.2.  This program is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY expressed or implied, including the
# implied warranties of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.  You should have
# received a copy of the GNU General Public License along with this program;
# if not, write to the Free Software Foundation, Inc., 51 Franklin Street,
# Fifth Floor, Boston, MA 02110-1301, USA. Any Red Hat trademarks that are
# incorporated in the source code or documentation are not subject to the GNU
# General Public License and may only be used or replicated with the express
# permission of Red Hat, Inc.

# Reload the customer jboss application

# Exit on any errors
set -e


if [ -f '/etc/libra/node.conf' ]
then
    . /etc/libra/node.conf
elif [ -f 'node.conf' ]
then
    . node.conf
else
    echo "node.conf not found.  Cannot continue" 1>&2
    exit 3
fi


function print_help {
    echo "Usage: $0 app-name username uuid"
    echo "Get application status"

    echo "$0 $@" | logger -p local0.notice -t libra_jboss_create
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

customer_id=$3
application="$1"

CUSTOMER_HOME="$libra_dir/$customer_id/"
APP_DIR="$CUSTOMER_HOME/jbossas/$application"

#
# Start application
#

runuser --shell /bin/sh "$customer_id" "$APP_DIR/${application}_ctl.sh" reload
