#!/bin/bash

# Copyright © 2010 Mike McGrath All rights reserved
# Copyright © 2010 Red Hat, Inc. All rights reserved

# This copyrighted material is made available to anyone wishing to use, modify,
# copy, or redistribute it subject to the terms and conditions of the GNU
# General Public License v.2.  This program is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY expressed or implied, including the
# implied warranties of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.  You should have
# received a copy of the GNU General Public License along with this program;
# if not, write to the Free Software Foundation, Inc., 51 Franklin Street,
# Fifth Floor, Boston, MA 02110-1301, USA. Any Red Hat trademarks that are
# incorporated in the source code or documentation are not subject to the GNU
# General Public License and may only be used or replicated with the express
# permission of Red Hat, Inc.

# Destroys metrics instance

function print_help {
    echo "Usage: $0 app-name namespace uuid"

    echo "$0 $@" | logger -p local0.notice -t libra_metrics_deconfigure
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

CART_DIR=${CART_DIR:=/usr/libexec/li/cartridges}
source ${CART_DIR}/abstract/info/lib/util

app_type="metrics-0.1"
setup_embedded_deconfigure "$1" $2 $3

METRICS_DIR=`echo $APP_HOME/metrics-0.1 | tr -s /` # ensure that there aren't double /'s
METRICS_CTL_SCRIPT="$METRICS_DIR/${application}_metrics_ctl.sh"

#
# Stop app
#
run_as_user "$METRICS_CTL_SCRIPT stop" || warning "Failed to stop ${application}" 121

confirm_pid_gone "${METRICS_DIR}/run/httpd.pid"

confirm_log_files_inactive "$METRICS_DIR/logs"

#
# Remove environment variables
#
/bin/rm -f $APP_HOME/.env/OPENSHIFT_METRICS_APP_DIR $APP_HOME/.env/OPENSHIFT_METRICS_CTL_SCRIPT $APP_HOME/.env/OPENSHIFT_METRICS_IP


# Remove metrics dir. This MUST be after stopping metrics as the CTL script relies on these.
runcon -l s0-s0:c0.c1023 rm -rf "$METRICS_DIR"

#
# Remove ProxyPass definition from apache
#
rm -f /etc/httpd/conf.d/libra/${uuid}_${namespace}_${application}/metrics-0.1.conf || warning "Could not remove metrics apache definition" 156

/sbin/service httpd configtest 2> /dev/null && /sbin/service httpd graceful || warning "Failed to restart master httpd, please contact support" 120
