#!/bin/bash

# Destroys metrics instance

function print_help {
    echo "Usage: $0 app-name namespace uuid"

    echo "$0 $@" | logger -p local0.notice -t stickshift_metrics_deconfigure
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

cartridge_type="metrics-0.1"
source "/etc/stickshift/stickshift-node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_embedded_deconfigure "$1" $2 $3

METRICS_DIR=$(get_cartridge_instance_dir "$cartridge_type")
METRICS_CTL_SCRIPT="$METRICS_DIR/${application}_metrics_ctl.sh"

#
# Stop app
#
run_as_user "$METRICS_CTL_SCRIPT stop" || warning "Failed to stop ${application}" 121

confirm_pid_gone "${METRICS_DIR}/run/httpd.pid"

confirm_log_files_inactive "$METRICS_DIR/logs"

#
# Remove environment variables
#
/bin/rm -f $APP_HOME/.env/OPENSHIFT_METRICS_GEAR_DIR $APP_HOME/.env/OPENSHIFT_METRICS_CTL_SCRIPT $APP_HOME/.env/OPENSHIFT_METRICS_IP


# Remove metrics dir. This MUST be after stopping metrics as the CTL script relies on these.
runcon -l s0-s0:c0.c1023 rm -rf "$METRICS_DIR"

#
# Remove ProxyPass definition from apache
#
rm -f /etc/httpd/conf.d/stickshift/${uuid}_${namespace}_${application}/metrics-0.1.conf || warning "Could not remove metrics apache definition" 156

${CARTRIDGE_BASE_PATH}/abstract/info/bin/httpd_singular graceful || warning "Failed to restart master httpd, please contact support" 120
