#!/bin/bash

# Move to a new ip

# Exit on any errors
set -e

source "/etc/stickshift/stickshift-node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/apache
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/network

load_node_conf

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done

[ $# -eq 3 ] || print_help

namespace=`basename $2`
application="$1"
uuid=$3

setup_basic_vars

CART_INFO_DIR=$CARTRIDGE_BASE_PATH/embedded/metrics-0.1/info

METRICS_DIR="$APP_HOME/metrics-0.1"
observe_setup_var_lib_dir "$METRICS_DIR"

METRICS_IP=`embedded_find_open_ip $uid $APP_HOME`
echo "export OPENSHIFT_METRICS_IP='$METRICS_IP'" > $APP_HOME/.env/OPENSHIFT_METRICS_IP
$CART_INFO_DIR/bin/deploy_httpd_config.sh $application $uuid $METRICS_IP
$CART_INFO_DIR/bin/deploy_httpd_proxy.sh $application $namespace $uuid $METRICS_IP

restart_httpd_graceful
