#!/bin/bash

# Restarts instance

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Stop a running application and disable it"

    echo "$0 $@" | logger -p local0.notice -t libra_phpmyadmin_restart
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

CART_DIR=/usr/libexec/li/cartridges
source ${CART_DIR}/abstract/info/lib/util

setup_basic_hook "$1" $2 $3

METRICS_DIR=`echo $APP_HOME/metrics-0.1 | tr -s /` # ensure that there aren't double /'s
METRICS_CTL_SCRIPT="$METRICS_DIR/${application}_metrics_ctl.sh"

#
# Start application
#
rm -f "$METRICS_DIR/run/stop_lock"
run_as_user "$METRICS_CTL_SCRIPT restart"
