#!/bin/bash

# Gets status of instance

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Stop a running application and disable it"

    echo "$0 $@" | logger -p local0.notice -t stickshift_metrics_status
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

cartridge_type="metrics-0.1"
source "/etc/stickshift/stickshift-node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_basic_hook "$1" $2 $3

METRICS_DIR=$(get_cartridge_instance_dir "$cartridge_type")

#
# Start application
#
ADDRESS="$(awk '/Listen/{ print $2 }' $METRICS_DIR/conf.d/stickshift.conf)"
URL="http://$ADDRESS/server-status?auto"

if output=$(runuser --shell /bin/sh "$uuid" -c "/usr/bin/wget -qO- $URL" 2>&1)
then
    status_client_result "$output"
else
    client_result "Metrics is either stopped or inaccessible"
fi
