#!/bin/bash

# Start the application httpd instance

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Start a running application"

    echo "$0 $@" | logger -p local0.notice -t libra_httpd_start
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

CART_DIR=$(dirname $(dirname $(dirname $0)))
source ${CART_DIR}/info/bin/load_config.sh
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util
source "${GEAR_BASE_DIR}/$3/.env/OPENSHIFT_APP_DNS"
source "${GEAR_BASE_DIR}/$3/.env/OPENSHIFT_PROXY_PORT"

echo ${OPENSHIFT_APP_DNS}:${OPENSHIFT_PROXY_PORT}
