#!/bin/bash -e

USERNAME="$1"
IV="$2"
TOKEN="$3"

# import Libra node configuration
if [ -f '/etc/libra/node.conf' ]
then
    . /etc/libra/node.conf
elif [ -f 'node.conf' ]
then
    . node.conf
else
    echo "node.conf not found.  Cannot continue" 1>&2
    exit 3
fi

APP_HOME=`echo ${libra_dir}/${USERNAME} | tr -s '/'`

#
# Import env values so they can be used:
#
for f in $APP_HOME/.env/*
do
    . $f
done

BROKER_AUTH_DIR="$OPENSHIFT_HOMEDIR/.auth"

mkdir -p $BROKER_AUTH_DIR
echo "$IV" > $BROKER_AUTH_DIR/iv
echo "$TOKEN" > $BROKER_AUTH_DIR/token

chown root.$OPENSHIFT_APP_UUID -R $BROKER_AUTH_DIR
chmod 0750 $BROKER_AUTH_DIR
chmod 0640 $BROKER_AUTH_DIR/*

echo "export OPENSHIFT_BROKER_AUTH_IV_FILE='$OPENSHIFT_HOMEDIR/.auth/iv'" > $OPENSHIFT_HOMEDIR/.env/OPENSHIFT_BROKER_AUTH_IV_FILE
echo "export OPENSHIFT_BROKER_AUTH_TOKEN_FILE='$OPENSHIFT_HOMEDIR/.auth/token'" > $OPENSHIFT_HOMEDIR/.env/OPENSHIFT_BROKER_AUTH_TOKEN_FILE
