#!/bin/bash -e

USERNAME="$1"
KEY="$2"
VALUE="$3"

CART_DIR=/usr/libexec/li/cartridges
source ${CART_DIR}/li-controller/info/lib/util

load_node_conf

APP_HOME=`echo ${libra_dir}/${USERNAME} | tr -s '/'`

echo "export $KEY='$VALUE'" > $APP_HOME/.env/$KEY