#!/bin/bash -e
USERNAME="$1"

CART_DIR=/usr/libexec/li/cartridges
source ${CART_DIR}/li-controller/info/lib/util

load_node_conf

APP_HOME=`echo ${libra_dir}/${USERNAME} | tr -s '/'`

#
# Import env values so they can be used:
#
for f in $APP_HOME/.env/*
do
    . $f
done

BROKER_AUTH_DIR="$OPENSHIFT_HOMEDIR/.auth"

rm -rf $BROKER_AUTH_DIR
rm -f $OPENSHIFT_HOMEDIR/.env/OPENSHIFT_BROKER_AUTH_IV_FILE
rm -f $OPENSHIFT_HOMEDIR/.env/OPENSHIFT_BROKER_AUTH_TOKEN_FILE
