#!/bin/bash -e

USERNAME="$1"
KEY="$2"

CART_DIR=/usr/libexec/li/cartridges
source ${CART_DIR}/li-controller/info/lib/util

load_node_conf

APP_HOME=`echo ${libra_dir}/${USERNAME} | tr -s '/'`

if [ -f $APP_HOME/.env/$KEY ]
then
    rm $APP_HOME/.env/$KEY
fi