#!/bin/bash -e
USERNAME="$1"

# import Libra node configuration
if [ -f '/etc/libra/node.conf' ]
then
    . /etc/libra/node.conf
elif [ -f 'node.conf' ]
then
    . node.conf
else
    echo "node.conf not found.  Cannot continue" 1>&2
    exit 3
fi

APP_HOME=`echo ${libra_dir}/${USERNAME} | tr -s '/'`

#
# Import env values so they can be used:
#
for f in $APP_HOME/.env/*
do
    . $f
done

BROKER_AUTH_DIR="$OPENSHIFT_HOMEDIR/.auth"

rm -rf $BROKER_AUTH_DIR
rm -f $OPENSHIFT_HOMEDIR/.env/OPENSHIFT_BROKER_AUTH_IV_FILE
rm -f $OPENSHIFT_HOMEDIR/.env/OPENSHIFT_BROKER_AUTH_TOKEN_FILE
