#!/bin/bash -e

USERNAME="$1"
KEY="$2"

# import Libra node configuration
if [ -f '/etc/libra/node.conf' ]
then
    . /etc/libra/node.conf
elif [ -f 'node.conf' ]
then
    . node.conf
else
    echo "node.conf not found.  Cannot continue" 1>&2
    exit 3
fi

APP_HOME=`echo ${libra_dir}/${USERNAME} | tr -s '/'`

rm $APP_HOME/.env/$KEY