#!/bin/bash

# Copyright © 2010 Mike McGrath All rights reserved
# Copyright © 2010 Red Hat, Inc. All rights reserved

# This copyrighted material is made available to anyone wishing to use, modify,
# copy, or redistribute it subject to the terms and conditions of the GNU
# General Public License v.2.  This program is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY expressed or implied, including the
# implied warranties of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.  You should have
# received a copy of the GNU General Public License along with this program;
# if not, write to the Free Software Foundation, Inc., 51 Franklin Street,
# Fifth Floor, Boston, MA 02110-1301, USA. Any Red Hat trademarks that are
# incorporated in the source code or documentation are not subject to the GNU
# General Public License and may only be used or replicated with the express
# permission of Red Hat, Inc.

# Destroys http instance

if [ -f '/etc/libra/node.conf' ]
then
    . /etc/libra/node.conf
elif [ -f 'node.conf' ]
then
    . node.conf
else
    echo "node.conf not found.  Cannot continue" 1>&2
    exit 3
fi

if [ -f '/etc/libra/node_data.conf' ]
then
    . /etc/libra/node_data.conf
elif [ -f 'node_data.conf' ]
then
    . node_data.conf
else
    echo "node_data.conf not found.  Cannot continue" 1>&2
    exit 3
fi

function print_help {
    echo "Usage: $0 app-name namespace uuid rhlogin"

    echo "$0 $@" | logger -p local0.notice -t libra_wsgi_deconfigure
    exit 1
}

function error {
    echo "$1" 1>&2
    exit "$2"
}

function destroy_repo {
    application="$1"
    uuid="$2"
    APP_HOME="${libra_dir}/${uuid}"

    if [ ! -d $APP_HOME ]; then echo "ERROR: Application ${uuid} not found!  Please create." 1>&2; fi

    GIT_DIR=$APP_HOME/git/$application.git
    rm -rf $GIT_DIR || error "Could not remove ${application}" 108
}

function rm_symlink {
    # Check if unobfuscate is set in /etc/libra/node.conf
    # If it is set, remove symlink

    namespace=$1
    appname=$2

    if [ $unobfuscate -eq 1 ]
    then        
        rm "${libra_dir}/${appname}-${namespace}"
    fi
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 4 ] || print_help

namespace=`basename $2`
application="$1"
uuid=$3
rhlogin=$4

APP_HOME="$libra_dir/$uuid/"
APP_DIR="$APP_HOME/$application"

uid=$(id -u "$uuid")
c_val="c$(($uid/1023)),c$(($uid%1023))"

#
# Destroy git app repo
#

destroy_repo $application $uuid

[ ! -d "$APP_DIR" ] && echo "${application} does not exist" 1>&2

runuser --shell /bin/sh "$uuid" -c "runcon -t libra_t -l s0:$c_val $APP_DIR/${application}_ctl.sh stop" || echo "Failed to stop ${application}" 1>&2
/usr/sbin/lsof -t "$APP_DIR/logs/error_log" | /usr/bin/xargs /bin/kill -9


# Confirm pid is gone before removing apps
i=0
while [ -f ${APP_DIR}/run/httpd.pid ] && [ $i -lt 30 ]
    do
    sleep .1
    i=$(($i + 1))
done
runcon -l s0-s0:c0.c1023 rm -rf "$APP_DIR"

rm_symlink $namespace $application

#
# Remove virtualhost definition for apache
#
rm -rf /etc/httpd/conf.d/libra/${uuid}_${namespace}_${application}.conf || echo "Could not remove apache definition" 1>&2
/sbin/service httpd configtest 2> /dev/null && /sbin/service httpd graceful || echo "Failed to restart master httpd, please contact support" 1>&2
