.\" Process this file with
.\" groff -man -Tascii rhc-create-domain.1
.\"
.TH RHC_CREATE_DOMAIN 1 "JANUARY 2011" Linux "User Manuals"
.SH NAME
rhc-create-domain \- creates a new Libra domain namespace with a user
.SH SYNOPSIS
.B rhc-create-domain [-p
.I password
.B ] [-a] [-d] [-h]
.B -l
.I rhlogin
.B -n
.I namespace
.SH DESCRIPTION
.B rhc-create-domain
create a new domain at rhcloud.com.  Once created
this user will be able to create and control
applications under their domain namespace.

Running
.B rhc-create-domain
will cause a new ssh key to be created in ssh
dir at
.I ~/.ssh/libra_id_rsa

Once created run
.BR rhc-create-app (1)
to create new applications or run
.BR rhc-ctl-app (1)
to control created applications.
.SH OPTIONS
.IP "-n|--namespace namespace"
Desired namespace to create.  Alphanumeric
.IP "-l|--rhlogin login"
Red Hat login
.IP "-p|--password password"
RHLogin password
.IP "-a|--alter"
Alter an existing user (change email or ssh key)
.IP -d|--debug
Enable debugging / verbose output
.IP -h|--help
Display help menu
.SH FILES
.I /etc/openshift/express.conf
.RS
The system wide configuration file. See
.BR express.conf (5)
for further details
.RE
.I ./express.conf
.RS
Local configuration file. See
.BR express.conf (5)
for further details.
.RE
.I ~/.openshift/express.conf
.RS
Per user configuration file. See
.BR express.conf (5)
for further details.
.RE
.SH BUGS
Please contact the Red Hat Libra team.
TODO: ADD EXTERNAL BUG TRACKER OR LIBRA TEAM CONTACT EMAIL
.SH AUTHOR
Mike McGrath <mmcgrath@redhat.com>, Jim Jagielski <jimjag@redhat.com>
.SH "SEE ALSO"
.BR rhc-create-user (1),
.BR rhc-ctl-app (1),
.BR rhc-snapshot(1),
.BR rhc-user-info(1),
.BR express.conf (5)
