.\" Process this file with
.\" groff -man -Tascii rhc-create-domain.1
.\"
.TH CTL_APP 1 "JANUARY 2011" Linux "User Manuals"
.SH NAME
rhc-ctl-app \- Control an existing rhcloud.com application
.SH SYNOPSIS
.B rhc-ctl-app [-n
.I namespace
.B ]
.B [-a
.I application_name
.B ]
.B [-t
.I framework_type
.B ]
.B [-c
.I command
.B ] [-b] [-d] [-h]
.SH DESCRIPTION
.B rhc-ctl-app
controls an existing rhcloud.com application.  To create
an application use the
.BR rhc-create-app (1)
command.

.BR command
options include start, stop, restart, reload, status and
destroy.  Note that
.BR destroy
is not reversable and will stop your application from
then remove the application and repo from the remote
server.  No local changes are made.

.SH OPTIONS
.IP "-n|--namespace namespace"
Desired namespace to create.  Alphanumeric
.IP "-a|--app application_name"
Name of application to create
.IP "-t|--type framework_type"
Framework type to create.  Currently only php-5.3.2 is supported
.IP "-c|--command command"
The command to send to remote server (start|stop|restart|reload|status|destroy)
.IP -b|--bypass
Bypass any TOS/SLA warnings and notifications
.IP -d|--debug
Enable debugging / verbose output
.IP -h|--help
Display help menu
.SH FILES
.I /etc/libra.conf
.RS
The system wide configuration file. See
.BR libra.conf (5)
for further details
.RE
.I ~/.libra
.RS
Per user configuration file. See
.BR libra.conf (5)
for further details.
.RE
.SH BUGS
Please contact the Red Hat Libra team.
TODO: ADD EXTERNAL BUG TRACKER OR LIBRA TEAM CONTACT EMAIL
.SH AUTHOR
Mike McGrath <mmcgrath@redhat.com>
.SH "SEE ALSO"
.BR rhc-create-domain (1),
.BR rhc-create-app (1),
.BR libra.conf (5),
