.\" Process this file with
.\" groff -man -Tascii rhc-create-user.1
.\"
.TH CREATE_USER 1 "JANUARY 2011" Linux "User Manuals"
.SH NAME
rhc-create-user \- creates a new Libra user
.SH SYNOPSIS
.B rhc-create-user [-l
.I rhlogin
.B ]
.B [-p
.I password
.B ]
.B [-n
.I namespace
.B ] [-d] [-h]
.SH DESCRIPTION
.B rhc-create-domain
create a new domain at rhcloud.com.  Once created
this user will be able to create and control
applications.

Running
.B rhc-create-domain
will cause a new ssh key to be created in ssh
dir at
.I ~/.ssh/id_rsa_libra

Once created run
.BR rhc-create-app (1)
to create new applications or run
.BR rhc-ctl-app (1)
to control created applications.
.SH OPTIONS
.IP "-n|--namespace namespace"
Desired namespace to create.  Alphanumeric
.IP "-l|--rhlogin login"
Red Hat login (often email) to use
.IP "-p|--password password"
RHLogin password (often email)
.IP "-a|--alter"
Alter an existing user (change email or ssh key)
.IP -d|--debug
Enable debugging / verbose output
.IP -h|--help
Display help menu
.SH FILES
.I /etc/libra/libra.conf
.RS
The system wide configuration file. See
.BR client.conf (5)
for further details
.RE
.I ./libra.conf
.RS
Local configuration file. See
.BR client.conf (5)
for further details.
.RE
.I ~/.li/libra.conf
.RS
Per user configuration file. See
.BR client.conf (5)
for further details.
.RE
.SH BUGS
Please contact the Red Hat Libra team.
.SH AUTHOR
Mike McGrath <mmcgrath@redhat.com>
.SH "SEE ALSO"
.BR rhc-create-app (1),
.BR rhc-ctl-app (1),
.BR libra.conf (5),
