source 'http://rubygems.org'

gem 'rails', '~> 3.0.10'
gem 'json'
gem 'parseconfig'
gem 'mongo'
gem 'xml-simple'
gem 'rack'
gem 'rest-client'
gem 'stickshift-controller'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
group :development, :test do
  # The require part from http://tinyurl.com/3pf68ho
  gem 'mocha', :require => nil
end
