#!/bin/bash

# Copyright © 2010 Mike McGrath All rights reserved
# Copyright © 2010 Red Hat, Inc. All rights reserved

# This copyrighted material is made available to anyone wishing to use, modify,
# copy, or redistribute it subject to the terms and conditions of the GNU
# General Public License v.2.  This program is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY expressed or implied, including the
# implied warranties of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.  You should have
# received a copy of the GNU General Public License along with this program;
# if not, write to the Free Software Foundation, Inc., 51 Franklin Street,
# Fifth Floor, Boston, MA 02110-1301, USA. Any Red Hat trademarks that are
# incorporated in the source code or documentation are not subject to the GNU
# General Public License and may only be used or replicated with the express
# permission of Red Hat, Inc.

# Destroys http instance

if [ -f '/etc/libra/node.conf' ]
then
    . /etc/libra/node.conf
elif [ -f 'node.conf' ]
then
    . node.conf
else
    echo "node.conf not found.  Cannot continue" 1>&2
    exit 3
fi

if [ -f '/etc/libra/node_data.conf' ]
then
    . /etc/libra/node_data.conf
elif [ -f 'node_data.conf' ]
then
    . node_data.conf
else
    echo "node_data.conf not found.  Cannot continue" 1>&2
    exit 3
fi

function print_help {
    echo "Usage: $0 app-name username"

    echo "$0 $@" | logger -p local0.notice -t libra_http_create
    exit 1
}

function error {
    echo "$1" 1>&2
    exit "$2"
}

function destroy_repo {
    application="$1"
    uuid="$2"
    CUSTOMER_HOME="${libra_dir}/${uuid}"

    if [ ! -d $CUSTOMER_HOME ]; then echo "ERROR: Customer ${uuid} not found!  Please create." 1>&2; fi

    GIT_DIR=$CUSTOMER_HOME/git/$application.git
    rm -rf $GIT_DIR || error "Could not remove ${application}" 108
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

namespace=`basename $2`
application="$1"
uuid=$3

CUSTOMER_HOME="$libra_dir/$uuid/"
APP_DIR="$CUSTOMER_HOME/wsgi/$application"

#
# Destroy git app repo
#

destroy_repo $application $uuid

#
# Create http base for application, every app gets its own apache instance
#

[ ! -d "$APP_DIR" ] && echo "${application} does not exist" 1>&2

runuser --shell /bin/sh "$uuid" $APP_DIR/${application}_ctl.sh stop || echo "Failed to stop ${application}" 1>&2

range_one=$(echo $IP | awk -F\. '{ print $3 }')
range_two=$(echo $IP | awk -F\. '{ print $4 }')


# Confirm pid is gone before removing apps
i=0
while [ -f ${APP_DIR}/run/httpd.pid ] && [ $i -lt 30 ]
    do
    sleep .1
    i=$(($i + 1))
done
#rm -rf "$APP_DIR"
runcon -l s0-s0:c0.c1023 rm -rf "$APP_DIR"

#
# Remove virtualhost definition for apache
#
rm -rf /etc/httpd/conf.d/${uuid}_${namespace}_${application}.conf || echo "Could not remove apache definition" 1>&2
/sbin/service httpd configtest 2> /dev/null && /sbin/service httpd graceful || echo "Failed to restart master httpd, please contact support" 1>&2
