<?php
/*
 * Implementation of hook_init().
 */
function modals_init() {
  // Add our ctools to the page
  ctools_include('modal');
  ctools_include('ajax');
  ctools_modal_add_js();
  // Add a new style for this popup.
  drupal_add_js(array(
    'join-modal-box' => array(
      'modalSize' => array(
        'type' => 'fixed',
        'width' => (int)400,
        'height' => (int)200,
  ),
      'animation' => 'fadeIn',
      'animationSpeed' => 'medium',
  ),
  ),
  'setting');
}

/*
 * Implementation of hook_menu().
 */
function modals_menu() {
  $items = array();

  $items['modals/%ctools_js/join/%node'] = array(
    'title' => 'Join a Group',
    'page callback' => 'modals_join_group',
    'page arguments' => array(1,3),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function modals_join_group($js = NULL, $node = NULL) {
  if ($js) {
    global $user;
    module_load_include('inc', 'og', 'og.pages');
    $form_state = array(
      'title' => t('Join Group'),
      'ajax' => TRUE,
      'args' => array($node->nid, $node, $user),
    );
    $output = ctools_modal_form_wrapper('og_confirm_subscribe', $form_state);
    if (empty($output)) {
      // empty $output signifies success, so we'll use it as our $commands array
      $output = array();
      if(isset($_REQUEST['destination'])) {
        $output[] = ctools_ajax_command_redirect($_REQUEST['destination']);
      }
      else {
        $output[] = ctools_ajax_command_redirect('node/'. $node->nid);
      }
    }
    ctools_ajax_render($output);
  }
}