#!/bin/bash

# Copyright © 2010 Mike McGrath All rights reserved
# Copyright © 2010 Red Hat, Inc. All rights reserved

# This copyrighted material is made available to anyone wishing to use, modify,
# copy, or redistribute it subject to the terms and conditions of the GNU
# General Public License v.2.  This program is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY expressed or implied, including the
# implied warranties of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.  You should have
# received a copy of the GNU General Public License along with this program;
# if not, write to the Free Software Foundation, Inc., 51 Franklin Street,
# Fifth Floor, Boston, MA 02110-1301, USA. Any Red Hat trademarks that are
# incorporated in the source code or documentation are not subject to the GNU
# General Public License and may only be used or replicated with the express
# permission of Red Hat, Inc.

# Move to a new ip

# Exit on any errors
set -e

source ../bin/load_config.sh
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/apache
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/network

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done

[ $# -eq 3 ] || [ $# -eq 4 ] || print_help

namespace=`basename $2`
application="$1"
uuid=$3
idle=false
if [ "$4" == "--idle" ]
then
  idle=true
fi

setup_basic_vars

. $APP_HOME/.env/OPENSHIFT_APP_TYPE

CART_INFO_DIR=$CARTRIDGE_BASE_PATH/$OPENSHIFT_APP_TYPE/info

unobfuscate_app_home $uuid $namespace $application

observe_setup_app_home
observe_setup_app_and_git_dirs

#
# Find an open localhost IP
#
IP=`find_open_ip $uid $uuid`
echo "export OPENSHIFT_INTERNAL_IP='$IP'" > $APP_HOME/.env/OPENSHIFT_INTERNAL_IP
if [ -f $CART_INFO_DIR/bin/deploy_httpd_config.sh ]
then
  $CART_INFO_DIR/bin/deploy_httpd_config.sh $application $uuid $IP
fi
run_as_user "${CARTRIDGE_BASE_PATH}/abstract/info/bin/redeploy_config_dir.sh"

. $APP_HOME/.env/OPENSHIFT_INTERNAL_IP

#
# Create virtualhost definition for apache
#
export CART_INFO_DIR
if [ -f $CART_INFO_DIR/bin/deploy_httpd_proxy.sh ]
then
  $CART_INFO_DIR/bin/deploy_httpd_proxy.sh $application $namespace $uuid $OPENSHIFT_INTERNAL_IP
else
  $CARTRIDGE_BASE_PATH/abstract/info/bin/deploy_httpd_proxy.sh $application $namespace $uuid $OPENSHIFT_INTERNAL_IP
fi

if $idle
then
  rhc-idler -u $uuid
fi

restart_httpd_graceful
