#!/bin/bash

# Remove httpd proxy

# Exit on any errors
set -e

CART_DIR=/usr/libexec/li/cartridges

source ${CART_DIR}/abstract/info/lib/util

load_node_conf

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Remove httpd proxy for an application"

    echo "$0 $@" | logger -p local0.notice -t libra_remove_httpd_proxy
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done

[ $# -eq 3 ] || print_help

namespace=`basename $2`
application="$1"
uuid=$3

rm_unobfuscated_app_home $namespace $application

rm -rf "/etc/httpd/conf.d/libra/${uuid}_${namespace}_${application}.conf" "/etc/httpd/conf.d/libra/${uuid}_${namespace}_${application}"
