#!/usr/bin/env ruby

require 'rubygems'
require 'parseconfig'
require 'thor'
require 'fileutils'
require 'aws'
require 'json'
require 'pp'

class Accounts < Thor
  include Thor::Actions

  no_tasks do
    def connect
      # This will verify the Amazon SSL connection
      Rightscale::HttpConnection.params[:ca_file] = "/etc/pki/tls/certs/ca-bundle.trust.crt"

      config = nil
      begin
        config = ParseConfig.new(File.expand_path("~/.awscred"))
      rescue StandardError => e
        puts <<-eos
          Couldn't access credentials in ~/.awscred

          Please create a file with the following format:
            AWSAccessKeyId=<ACCESS_KEY>
            AWSSecretKey=<SECRET_KEY>
        eos
        raise "Error - no credentials"
      end

      # Return the AMZ connection
      Aws::S3Interface.new(config.get_value("AWSAccessKeyId"), 
                           config.get_value("AWSSecretKey"), 
                           params = {:logger => Logger.new('/dev/null')})
    end
  end

  desc "migrate BUCKET FROM TO", "Migrate an S3 entry from one key name to another"
  method_option :dryrun, :type => :boolean, :desc => "Don't actually perform any changes"
  def migrate(bucket, from, to)
    s3 = connect

    # Make sure we can access the 'from' key
    from_key = 'user_info/' + from
    user_key = from_key + "/user.json"
    user_result = s3.head(bucket, user_key)
    raise "Couldn't find 'from' key" unless user_result

    # Make sure the 'to' key doesn't already exist
    to_key = 'user_info/' + to
    to_user_key = to_key + "/user.json"
    begin
      to_user_result = s3.head(bucket, to_user_key)
      raise "'to' user already exists" if to_user_result
    rescue Aws::AwsError
      # Ignore - we don't want the target to already exist
    end

    # Now find the apps to migrate
    apps = s3.list_bucket(bucket.dup, {'prefix' => from_key + "/apps"})
    apps_migrate = {}

    apps.each do |app|
      app_key = app[:key]
      app_name = app_key.split("/")[-1]
      apps_migrate[app_key] = to_key + "/apps/" + app_name
    end

    puts "Migration Output:"
    puts user_key + " -> " + to_user_key
    apps_migrate.each_pair do |key, val|
      puts key + " -> " + val
    end

    unless options.dryrun?
      puts "Moving from #{user_key} to #{to_user_key}..."
      puts "Bucket = #{bucket}"
      s3.rename(bucket, user_key, to_user_key)
      apps_migrate.each_pair do |key, val|
        s3.rename(bucket, key, val)
      end
      puts "Done."

      puts "Sleeping to allow S3 to sync..."
      sleep 1

      puts "Updating rhlogin in json file"
      json = JSON.parse(s3.get(bucket, to_user_key)[:object])
      puts "Updating rhlogin from '#{json['rhlogin']}' to '#{to}'"
      json['rhlogin'] = to
      s3.put(bucket, to_user_key, JSON.generate(json))
      puts "Done."
    end
  end

  desc "bulk BUCKET INPUT_FILE", "Migrate a list of accounts in 'from/to' format"
  method_option :dryrun, :type => :boolean, :desc => "Don't actually perform any changes"
  def bulk(bucket, input_file)
    s3 = connect
    File.open(File.expand_path(input_file, "r")) do |file|
      file.readlines.each do |line|
        from, to = line.chomp.split("/")
        puts "Migrating user: #{from} to #{to}"
        migrate(bucket, from, to)
      end
    end
  end
end

Accounts.start
