#!/bin/bash

# Copyright © 2010 Mike McGrath All rights reserved
# Copyright © 2011 Scott Stark All rights reserved
# Copyright © 2010 Red Hat, Inc. All rights reserved

# This copyrighted material is made available to anyone wishing to use, modify,
# copy, or redistribute it subject to the terms and conditions of the GNU
# General Public License v.2.  This program is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY expressed or implied, including the
# implied warranties of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.  You should have
# received a copy of the GNU General Public License along with this program;
# if not, write to the Free Software Foundation, Inc., 51 Franklin Street,
# Fifth Floor, Boston, MA 02110-1301, USA. Any Red Hat trademarks that are
# incorporated in the source code or documentation are not subject to the GNU
# General Public License and may only be used or replicated with the express
# permission of Red Hat, Inc.

# Destroys the customer jboss instance

# The name of the jbossas cartridge dir under /usr/libexec/li/cartridges
jboss_version=jbossas-7.0.0

CART_DIR=${CART_DIR:=/usr/libexec/li/cartridges}

source ${CART_DIR}/li-controller/info/lib/selinux
source ${CART_DIR}/li-controller/info/lib/git
source ${CART_DIR}/li-controller/info/lib/util
source ${CART_DIR}/li-controller/info/lib/apache

load_node_conf

load_node_data_conf

function print_help {
    echo "Usage: $0 app-name namespace uuid"

    echo "$0 $@" | logger -p local0.notice -t libra_jboss_deconfigure
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

namespace=`basename $2`
application="$1"
uuid=$3

APP_HOME="$libra_dir/$uuid/"
APP_DIR="$APP_HOME/$application"
M2_DIR="$APP_HOME/.m2" # maven dir

if [ ! -d "$APP_DIR" ]
then
  exit 125
fi

uid=$(id -u "$uuid")
mcs_level=`openshift_mcs_level $uid`

#
# Destroy git repo
#
destroy_git_repo $application $uuid

stop_app

# Confirm pid is gone before removing apps
i=0
while [ -f ${APP_DIR}/run/jboss.pid ] && [ $i -lt 30 ]
    do
    sleep .1
    i=$(($i + 1))
done
#rm -rf "$APP_DIR"
runcon -l s0-s0:c0.c1023 rm -rf "$APP_DIR"

rm_unobfuscated_app_home $namespace $application

# remove the Maven repository.
runcon -l s0-s0:c0.c1023 rm -rf "$M2_DIR"

#
# Remove virtualhost definition for apache
#
rm_httpd_proxy $uuid $namespace $application
