#!/bin/bash

# Copyright © 2010 Red Hat, Inc. All rights reserved

# This copyrighted material is made available to anyone wishing to use, modify,
# copy, or redistribute it subject to the terms and conditions of the GNU
# General Public License v.2.  This program is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY expressed or implied, including the
# implied warranties of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.  You should have
# received a copy of the GNU General Public License along with this program;
# if not, write to the Free Software Foundation, Inc., 51 Franklin Street,
# Fifth Floor, Boston, MA 02110-1301, USA. Any Red Hat trademarks that are
# incorporated in the source code or documentation are not subject to the GNU
# General Public License and may only be used or replicated with the express
# permission of Red Hat, Inc.

# Confirms all required php bits are in place or fails

set -e


# The name of the jbossas cartridge dir under /usr/libexec/li/cartridges
jboss_version=jbossas-7.0.0

CART_DIR=/usr/libexec/li/cartridges
source ${CART_DIR}/abstract/info/lib/util

load_node_conf

[ -z "$CARTRIDGE_DIR" ] && CARTRIDGE_DIR="/usr/libexec/li/cartridges/${jboss_version}/"

function print_help {
    echo "Usage: uuid"
    exit 1
}

function quit {
    echo -e "$1" 1>&2
    exit 5
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done

[ $# -eq 1 ] || print_help

uuid=$1

JBOSS_HOME=/etc/alternatives/jbossas-7.0
PSQL_JDBC_JAR=/usr/share/java/postgresql-jdbc3.jar
PSQL_MODULE_SUBDIR=org/postgresql/jdbc/main

mkdir -p $JBOSS_HOME/modules/$PSQL_MODULE_SUBDIR
ln -fs $PSQL_JDBC_JAR  $JBOSS_HOME/modules/$PSQL_MODULE_SUBDIR

cat > $JBOSS_HOME/modules/$PSQL_MODULE_SUBDIR/module.xml  <<MEOF
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="urn:jboss:module:1.0" name="org.postgresql">
   <resources>
      <resource-root path="$(filename $PSQL_JDBC_JAR)"/>
   </resources>
   <dependencies>
      <module name="javax.api"/>
      <module name="javax.transaction.api"/>
   </dependencies>
</module>
MEOF


