#!/bin/bash

# Destroys rockmongo instance

function print_help {
    echo "Usage: $0 app-name namespace uuid"

    echo "$0 $@" | logger -p local0.notice -t stickshift_rockmongo_deconfigure
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done

[ $# -eq 3 ] || print_help

source "/etc/stickshift/stickshift-node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

app_type="rockmongo-1.1"
setup_embedded_deconfigure "$1" $2 $3

ROCKMONGO_DIR=`echo $APP_HOME/rockmongo-1.1 | tr -s /` # ensure that there aren't double /'s
ROCKMONGO_CTL_SCRIPT="$ROCKMONGO_DIR/${application}_rockmongo_ctl.sh"

#
# Stop app
#
run_as_user "$ROCKMONGO_CTL_SCRIPT stop" || warning "Failed to stop ${application}" 121

confirm_pid_gone "${ROCKMONGO_DIR}/run/httpd.pid"

confirm_log_files_inactive "$ROCKMONGO_DIR/logs"

#
# Remove environment variables
#
/bin/rm -f $APP_HOME/.env/OPENSHIFT_ROCKMONGO_GEAR_DIR $APP_HOME/.env/OPENSHIFT_ROCKMONGO_CTL_SCRIPT $APP_HOME/.env/OPENSHIFT_ROCKMONGO_IP 


# Remove rockmongo dir. This MUST be after stopping rockmongo as the CTL script relies on these.
runcon -l s0-s0:c0.c1023 rm -rf "$ROCKMONGO_DIR"

#
# Remove ProxyPass definition from apache
#
rm -f ${STICKSHIFT_HTTP_CONF_DIR}/${uuid}_${namespace}_${application}/rockmongo-1.1.conf || warning "Could not remove rockmongo apache definition" 156

/sbin/service httpd configtest 2> /dev/null && /sbin/service httpd graceful || warning "Failed to restart master httpd, please contact support" 120
