#!/bin/bash

# Move to a new ip

# Exit on any errors
set -e

source "/etc/stickshift/stickshift-node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/apache
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/network

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done

[ $# -eq 3 ] || print_help

namespace=`basename $2`
application="$1"
uuid=$3

setup_basic_vars

ROCKMONGO_DIR=`echo $APP_HOME/rockmongo-1.1 | tr -s /`

observe_setup_var_lib_dir "$ROCKMONGO_DIR"

CART_INFO_DIR=${CARTRIDGE_BASE_PATH}/embedded/rockmongo-1.1/info

. $APP_HOME/.env/OPENSHIFT_INTERNAL_IP
. $APP_HOME/.env/OPENSHIFT_MONGODB_DB_PORT

ROCKMONGO_IP=`embedded_find_open_ip $uid $APP_HOME`
echo "export OPENSHIFT_ROCKMONGO_IP='$ROCKMONGO_IP'" > $APP_HOME/.env/OPENSHIFT_ROCKMONGO_IP
$CART_INFO_DIR/bin/deploy_httpd_config.sh $application $uuid $ROCKMONGO_IP
$CART_INFO_DIR/bin/deploy_httpd_proxy.sh $application $namespace $uuid $ROCKMONGO_IP

sed -e "s,TEMPLATE_SET_MONGODB_HOST,$OPENSHIFT_INTERNAL_IP," \
    -e "s,TEMPLATE_SET_MONGODB_PORT,$OPENSHIFT_MONGODB_DB_PORT," \
    $CART_INFO_DIR/rockmongo/config.php > $ROCKMONGO_DIR/rockmongo/config.php

restart_httpd_graceful