#!/usr/bin/env ruby

require 'rubygems'
require 'coffee_script'

unless ARGV.length == 1
  puts "Usage: #{$0} path/to/script.coffee"
  exit 1
end

script = ARGV[0]

unless File.exists?(script)
  puts "File does not exist! #{script}"
  exit 1
end

puts CoffeeScript.compile File.read(script)
