    <footer>
      <div id="footer-nav">
        <div class="container">
          <div class="row">
            <nav class="span3">
              <header>
                <h3><a href="/developers">Developers</a></h3>
              </header>
              <ul class="unstyled">
                <li><a href="/get-started">Get Started</a></li>
                <li><a href="<?php print openshift_user_guide_url(); ?>">User Guide</a></li>
                <li><a href="/faq">FAQ</a></li>
                <li><a href="/developers/pricing">Pricing</a></li>
              </ul>
            </nav>
            <nav class="span3">
              <header>
                <h3><a href="/community">Community</a></h3>
              </header>
              <ul class="unstyled">
                <li><a href="/blogs">Blog</a></li>
                <li><a href="/forums/">Forum</a></li>
                <li><a href="http://webchat.freenode.net/?randomnick=1&amp;channels=openshift&amp;uio=d4">IRC Channel</a></li>
                <li><a href="mailto:openshift@redhat.com">Feedback</a></li>
              </ul>
            </nav>
            <nav class="span3">
              <header>
                <h3><a href="/get-involved">Get Involved</a></h3>
              </header>
              <ul class="unstyled">
                <li><a href="/open-source">Open Source</a></li>
                <li><a href="/partners">Partners</a></li>
                <li><a href="https://github.com/openshift">OpenShift on GitHub</a></li>
                <li><a href="/newsletter/signup">Newsletter sign up</a></li>
              </ul>
            </nav>
            <nav class="span3">
              <header>
                <h3><a href="<?php print $openshift_server_url; ?>/app/account">Account</a></h3>
              </header>
              <ul class="unstyled">
                <li><a href="/legal/services_agreement">Terms of Service</a></li>
                <li><a href="/legal/openshift_privacy">Privacy Policy</a></li>
                <li><a href="/policy/security">Security Policy</a></li>
                <li><a href="/developers/pricing">Plans</a></li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
      <section id="copyright">
        <div class="container">
          <a href="https://www.redhat.com/">
            <img src="<?php print $openshift_server_url; ?>/app/assets/redhat.png" alt="Red Hat">
          </a>
          <div class="pull-right"><?php print $footer_message; ?></div>
        </div>
      </section>
    </footer>
    <!-- SiteCatalyst code version: H.23.3.
    Copyright 1996-2011 Adobe, Inc. All Rights Reserved
    More info available at http://www.omniture.com -->
    <div id="oTags">
    <script type="text/javascript" src="<?php print $openshift_server_url; ?>/app/assets/site/tracking.js"></script>
    <script type="text/javascript" src="<?php print $openshift_server_url; ?>/app/assets/site/s_code.js"></script>
    <script language="JavaScript" type="text/javascript"><!--
    /* You may give each page an identifying name, server, and channel on
    the next lines. */
    s.pageName="openshift | community | <?php print $head_title; ?>"
    s.server=""
    s.channel="<?php if($product): ?>OpenShift | Product | <?php print $product; ?><?php endif; ?>"
    s.heir1=""
    s.pageType=""
    s.prop1=""
    s.prop2=""
    s.prop3=""
    s.prop4=""
    s.prop5=""
    /* Conversion Variables */
    s.campaign=""
    s.state=""
    s.zip=""
    s.events=""
    s.products=""
    s.purchaseID=""
    s.eVar1=""
    s.eVar2=""
    s.eVar3=""
    s.eVar4=""
    s.eVar5=""
    s.eVar51="<?php if($product): ?><?php print $product; ?><?php endif; ?>"
    s.eVar27=""
    s.eVar28=""
    s.eVar29=""
    /************* DO NOT ALTER ANYTHING BELOW THIS LINE ! **************/
    var s_code=s.t();if(s_code)document.write(s_code)//--></script>
    <script language="JavaScript" type="text/javascript"><!--
    if(navigator.appVersion.indexOf('MSIE')>=0)document.write(unescape('%3C')+'\!-'+'-')
    //--></script><noscript><img src="http://redhat.122.2o7.net/b/ss/redhatopenshift/1/H.23.3--NS/0"
    height="1" width="1" border="0" alt="" /></noscript><!--/DO NOT REMOVE/-->
    <!-- End SiteCatalyst code version: H.23.3. -->
    </div>
    <div style="display:none;"> <?php # FIXME remove after sprint 10 ?>
    <script src="<?php print $openshift_server_url; ?>/app/status/status.js?id=outage" type="text/javascript"></script>
    </div>
  </body>
<?php print $closure; ?>
</script>
</html>
