#!/bin/bash

[ ! -z "$CRON_LIB_UTIL" ] && return 0
CRON_LIB_UTIL=true

function enable_cronjobs {
    CRON_DIR=${CRON_DIR:-"$APP_HOME/cron-1.4/"}
    /bin/su -s /bin/sh "$uuid" -c "runcon -t libra_t -l $mcs_level $CRON_DIR/${application}_cron_ctl.sh enable"
    wait_to_enable
}

function wait_to_enable {
    sleep 1
}

function disable_cronjobs {
    CRON_DIR=${CRON_DIR:-"$APP_HOME/cron-1.4/"}
    /bin/su -s /bin/sh "$uuid" -c "runcon -t libra_t -l $mcs_level $CRON_DIR/${application}_cron_ctl.sh disable"
}
