#!/bin/bash

# Publishes the mysql database connection information.

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Publish mysql database connection information"

    echo "$0 $@" | logger -p local0.notice -t libra_mysql_publish_conn_info
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

CART_DIR=/usr/libexec/li/cartridges
source ${CART_DIR}/abstract/info/lib/util

setup_configure "$1" $2 $3

import_env_vars

# Check scalability and setup entries accordingly.
if is_a_scalable_app; then
    mysql_host=$OPENSHIFT_APP_DNS
    mysql_port=$OPENSHIFT_DB_PROXY_PORT
    mysql_dburl="$OPENSHIFT_DB_TYPE://$OPENSHIFT_DB_USERNAME:$OPENSHIFT_DB_PASSWORD@$mysql_host:$mysql_port/"
    mysql_dbsocket=""
    echo "OPENSHIFT_DB_GEAR_USERHOST=$OPENSHIFT_APP_UUID@$mysql_host"
fi

echo "OPENSHIFT_DB_TYPE=$OPENSHIFT_DB_TYPE"
echo "OPENSHIFT_DB_HOST=${mysql_host:-$OPENSHIFT_DB_HOST}"
echo "OPENSHIFT_DB_PORT=${mysql_port:-$OPENSHIFT_DB_PORT}"
echo "OPENSHIFT_DB_URL=${mysql_dburl:-$OPENSHIFT_DB_URL}"
echo "OPENSHIFT_DB_USERNAME=$OPENSHIFT_DB_USERNAME"
echo "OPENSHIFT_DB_PASSWORD=$OPENSHIFT_DB_PASSWORD"
echo "OPENSHIFT_DB_SOCKET=${mysql_dbsocket:-$OPENSHIFT_DB_SOCKET}"
echo "OPENSHIFT_DB_MYSQL_51_DUMP=$OPENSHIFT_DB_MYSQL_51_DUMP"
echo "OPENSHIFT_DB_MYSQL_51_DUMP_CLEANUP=$OPENSHIFT_DB_MYSQL_51_DUMP_CLEANUP"
echo "OPENSHIFT_DB_MYSQL_51_EMBEDDED_TYPE=$OPENSHIFT_DB_MYSQL_51_EMBEDDED_TYPE"
echo "OPENSHIFT_DB_MYSQL_51_RESTORE=$OPENSHIFT_DB_MYSQL_51_RESTORE"

# Check what to do for : OPENSHIFT_DB_CTL_SCRIPT


