#!/bin/bash

# Copyright © 2010 Mike McGrath All rights reserved
# Copyright © 2010 Red Hat, Inc. All rights reserved

# This copyrighted material is made available to anyone wishing to use, modify,
# copy, or redistribute it subject to the terms and conditions of the GNU
# General Public License v.2.  This program is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY expressed or implied, including the
# implied warranties of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.  You should have
# received a copy of the GNU General Public License along with this program;
# if not, write to the Free Software Foundation, Inc., 51 Franklin Street,
# Fifth Floor, Boston, MA 02110-1301, USA. Any Red Hat trademarks that are
# incorporated in the source code or documentation are not subject to the GNU
# General Public License and may only be used or replicated with the express
# permission of Red Hat, Inc.

# Confirm user doesn't already exist

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 customername"
    exit 1
}

function quit {
    echo -e "$1" 1>&2
    exit 5
}

customer_id=$1

if ( [ -z "$customer_id" ])
then
    print_help
fi

groups "$customer_id" > /dev/null 2>&1 && quit "Customer $customer_id already exists"
[ -d "/var/lib/libra/${customer}" ] || quit "Customer namespace already exists!"
