<?php

function redhat_events_menu() {
  $items['events'] = array(
    'page callback' => redhat_events_page,
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function redhat_events_page(){

  $content = "<ul class='forum-navigation-links'>";

  $sort = $_GET['sort'];
  if (!$sort) {
    $sort = 'date';
  }
  if ($sort != 'country'){
    $content .= "<li><a href='events?sort=country'>View By Country</a></li>";
  }
  if ($sort != 'date'){
    $content .= "<li><a href='events'>View By Date</a></li>";
  }
  if ($sort != 'calendar'){
    $content .= "<li><a href='calendar'>Calendar View</a></li>";
  }
  $content .= "</ul>";

  if ($sort == 'country'){
    $content .= views_embed_view('event_view', 'block_2');
  }
  elseif ($sort == 'date'){
    $content .= views_embed_view('event_view', 'block_1');
  }
  return $content;

}

include_once('redhat_events.features.inc');
