<?php

function redhat_events_menu() {
  $items['events'] = array(
    'page callback' => redhat_events_page,
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function redhat_events_date_format_types() {
  return array(
    'redhat_events_date_format_short' => t('Events short'),
    'redhat_events_date_format_medium' => t('Events medium'),
    'redhat_events_date_format_mini_calendar' => t('Events mini calendar'),
  );
}

/*
* hook_date_formats
*/
function redhat_events_date_formats() {
  $formats = array();

  // Short date formats.
  $formats[] = array(
    'type' => 'redhat_events_date_format_short',
    'format' => 'D M j o',
    'locales' => array(),
  );
  $formats[] = array(
    'type' => 'redhat_events_date_format_medium',
    'format' => 'l F j, Y g:ma',
    'locales' => array(),
  );
  $formats[] = array(
    'type' => 'redhat_events_date_format_mini_calendar',
    'format' => 'D M',
    'locales' => array(),
  );
  return $formats;
}

function redhat_events_page(){

  $content = <<<BAR
    <div class="pull-right" style="margin-top:10px;">
      <a href="/community/events/ics" style="margin-right:10px;font-size:90%;">Add to my calendar</a>
      <a href="/community/events/feed">
        <img title="Subscribe to the events RSS feed" alt="RSS" src="/community/misc/feed.png" style="vertical-align:middle;" />
      </a>
    </div>
    <ul class="nav nav-tabs">
BAR;

  $sort = $_GET['sort'];
  if (!$sort) { $sort = 'date'; }
  $content .= "<li" . ($sort == 'date' ? " class='active'" : "") . "><a href='events'>View By Date</a></li>";
  $content .= "<li" . ($sort == 'country' ? " class='active'" : "") . "><a href='events?sort=country'>View By Country</a></li>";
  $content .= "<li" . ($sort == 'calendar' ? " class='active'" : "") . "><a href='calendar'>Calendar View</a></li>";
  $content .= "</ul>";

  if ($sort == 'country'){
    $content .= views_embed_view('event_view', 'block_2');
  }
  elseif ($sort == 'date'){
    $content .= views_embed_view('event_view', 'block_1');
  }

  return $content;

}

include_once('redhat_events.features.inc');
