#!/bin/bash

# Adds a gear to the haproxy configuration.

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Start a running application"

    echo "$0 $@" | logger -p local0.notice -t libra_httpd_start
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -gt 3 ] || print_help

# This doesn't work at this time because sourcing in /etc/libra/node.conf gives
# a permission denied issue -- think its how the connection-hooks are run.
if [ -n "$FIXED_CONNECTION_HOOK_PERMS_ISSUE" ]; then
    CART_DIR=/usr/libexec/li/cartridges
    source ${CART_DIR}/abstract/info/lib/util

    setup_basic_hook "$1" $2 $3

    import_env_vars
else
    # Import Environment Variables
    for f in ~/.env/*; do
        source $f
    done
fi

haproxy_cfg=$OPENSHIFT_APP_DIR/conf/haproxy.cfg
# Remove the first 3 args and process all the gear endpoints:
for ep in ${@:4}; do
    #  Add gear to the proxy configuration.
    #  Gear end-point is the form: $gear-dns-entry:$gear-port
    gear_name=$(echo "$ep" | cut -f 1 -d '.')
    echo "    server $gear_name $ep check fall 2 rise 3 inter 2000" >> "$haproxy_cfg"
done

