#!/bin/bash

# Set ssh endpoints for all gears where the application framework is running.
CART_NAME=haproxy
CART_VERSION=1.4

# Exit on any errors
set -e

function log_error() {
    echo "$0: $@" | logger -p local0.err -t stickshift_haproxy_set_git_url
    return ${1:-1}
}


function print_help() {
    echo "Usage: $0 app-name namespace uuid"
    echo "Start a running application"

    echo "$0 $@" | logger -p local0.notice -t stickshift_haproxy_set_git_url
    exit 1
}


function get_registered_endpoints() {
    [ -f "$HAPROXY_GEAR_REGISTRY" ]  &&  cat "$HAPROXY_GEAR_REGISTRY"
}


function register_gear_endpoint() {
    [ $# -lt 2 ]  &&  return 1

    #  Add gear endpoint to registry if it doesn't already exist.
    if ! grep "$2" "$HAPROXY_GEAR_REGISTRY" > /dev/null 2>&1; then
        echo "$2" >> "$HAPROXY_GEAR_REGISTRY"
    fi

    return 0
}


function unregister_gear() {
    [ $# -lt 2 ]  &&  return 1

    #  Check if the gear endpoint registry entry exists.
    if grep "$2" "$HAPROXY_GEAR_REGISTRY" > /dev/null 2>&1; then
        sed -i "/$2.*/d" "$HAPROXY_GEAR_REGISTRY"
        # tmpf=/tmp/gear-registry.db.$$
        # sed "/$2.*/d" "$HAPROXY_GEAR_REGISTRY"  > "$tmpf"
        # cat "$tmpf" > "$HAPROXY_GEAR_REGISTRY"
        # rm -f /tmp/gear-registry.db.$$
    fi
}


#
# main():
#
while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -gt 3 ] || print_help

source /etc/stickshift/stickshift-node.conf
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_configure "$1" $2 $3

import_env_vars

# Defines.
HAPROXY_CONF_DIR=$OPENSHIFT_GEAR_DIR/$CART_NAME-$CART_VERSION/conf
HAPROXY_GEAR_REGISTRY=$HAPROXY_CONF_DIR/gear-registry.db

# Array containing current endpoints.
declare -A curr_endpoints

#  Remove the first 3 args and process all the remaining args of the form
#  key=value. The values are the 'scp-like' endpoints for each gear.
kvargs=$(echo "${@:4}" | tr -d "\n" )
for arg in $kvargs; do
    ep=$(echo "$arg" | cut -f 2 -d '=' | tr -d "'")
    gear_name=gear-$(echo "$ep" | cut -f 2 -d '@' | cut -f 1 -d '.')
    curr_endpoints[$gear_name]="$ep"
    register_gear_endpoint "$gear_name" "$ep"  ||  :
done

# Get a list of all the registered endpoints and remove the endpoints which
# are not in the current set.
for gear_ep in $(get_registered_endpoints); do
    gear_name=gear-$(echo "$gear_ep" | cut -f 2 -d '@' | cut -f 1 -d '.')
    if [ -z "${curr_endpoints[$gear_name]}" ]; then
        unregister_gear "$gear_name" "$gear_ep"  ||  :
    fi
done
