#!/usr/bin/ruby

require 'rubygems'
require 'mcollective'
require 'fileutils'
require 'openshift'
require 'pp'


include MCollective::RPC
include Libra

options = rpcoptions do |parser, options|
    parser.define_head "Get info about a user"
    parser.banner = "Usage: rhc-get-user-info [options]"

    parser.on('-l', '--rhlogin RHLOGIN', "The unique rhlogin") do |rhlogin|
      options[:rhlogin] = rhlogin
    end
end

# Set the MCollective options
if options[:timeout] && options[:timeout] < 30
    options[:timeout] = 30
end
Libra.c[:rpc_opts] = options

# Check if rhlogin already exists
user = User.find(options[:rhlogin])
unless user
    puts "Could not find user with rhlogin #{options[:rhlogin]}"
    exit 1
end
user_info = {
    :rhlogin => user.rhlogin,
    :uuid => user.uuid,
    :namespace => user.namespace,
    :ssh_key => user.ssh
    }

app_info = {}

user.apps.each do |appname, app|
    app_info[appname] = {
        :framework => app['framework'],
        :creation_time => app['creation_time'],
        :uuid => app['uuid'],
        :embedded => app['embedded'],
        :aliases => app['aliases']
    }
end

puts "User Info:"
puts user_info.pretty_inspect

puts "App Info:"
puts app_info.pretty_inspect
