#!/usr/bin/env ruby

require "/var/www/libra/broker/config/environment"
require 'getoptlong'

def usage
    puts <<USAGE
== Synopsis

rhc-admin-create-district: Create a district

== Usage

rhc-admin-create-district OPTIONS

Options:
-h|--help
    Show Usage info
USAGE
end

opts = GetoptLong.new(
    ["--bypass",           "-b", GetoptLong::NO_ARGUMENT],    
    ["--help",             "-h", GetoptLong::NO_ARGUMENT]
)

args = {}
begin
    opts.each{ |k,v| args[k]=v }
rescue GetoptLong::Error => e
    usage
    exit -100
end


if args["--help"]
  usage
  exit 1
end

reply = ResultIO.new
begin
  district = District.new
  district.save
  reply.resultIO << "Successfully created district: #{district.uuid}" if reply.resultIO.string.empty?
rescue Cloud::Sdk::CdkException => e
  reply.errorIO << e.message
end

print "DEBUG OUTPUT:\n#{reply.debugIO.string}\n\n" unless reply.debugIO.string.empty?
print "ERROR OUTPUT:\n#{reply.errorIO.string}\n\n" unless reply.errorIO.string.empty?
print "#{reply.resultIO.string}\n" unless reply.resultIO.string.empty?
