#!/usr/bin/env ruby

require 'rubygems'
require 'getoptlong'
require 'json'

def usage
    puts <<USAGE
== Synopsis

rhc-admin-user-vip: Sets the vip flag on/off for a user

== Usage

rhc-admin-user-vip OPTIONS

Options:
-l|--login USER_LOGIN
  The login name of the user
-v|--vip 1|0
  Set or unset VIP status for the user
-h|--help
    Show Usage info
USAGE
end

opts = GetoptLong.new(
    ["--login",            "-l", GetoptLong::REQUIRED_ARGUMENT],
    ["--vip",              "-v", GetoptLong::REQUIRED_ARGUMENT],
    ["--help",             "-h", GetoptLong::NO_ARGUMENT]
)

args = {}
begin
    opts.each{ |k,v| args[k]=v }
rescue GetoptLong::Error => e
    usage
    exit -100
end

login     = args["--login"]
vip       = args["--vip"]

if login.nil? or vip.nil? or not (vip == "1" or vip == "0")
  print "Invalid login or VIP status\n"
  usage
  exit -100
end

require "/var/www/stickshift/broker/config/environment"

user = CloudUser.find(login)
if user.nil?
  print "User with login #{login} not found\n"
  exit -101
end

if vip == "1"
  user.vip = true
else
  user.vip = false
end
user.save
print "User #{user.login}'s vip status set to #{user.vip}\n"
