#!/usr/bin/env ruby

require 'rubygems'
require 'getoptlong'

def usage
    puts <<USAGE
== Synopsis

rhc-admin-remove-template: Remove an application template

== Usage

rhc-admin-remove-template OPTIONS

Options:
-u|--uuid UUID
  The UUID of the application template to remove.
-h|--help
    Show Usage info
USAGE
end

opts = GetoptLong.new(
  ["--uuid",             "-u", GetoptLong::REQUIRED_ARGUMENT],    
  ["--help",             "-h", GetoptLong::NO_ARGUMENT]
)

args = {}
begin
  opts.each{ |k,v| args[k]=v }
rescue GetoptLong::Error => e
  usage
  exit -100
end

uuid     = args["--uuid"]
if uuid.nil?
  print "Template UUIDnot provided\n"
  usage
  exit -100
end

require "/var/www/libra/broker/config/environment"

template = ApplicationTemplate.find(uuid)
if template.nil?
  print "Template with UUID #{uuid} not found\n"
else
  template.delete
  print "Template with UUID #{template.uuid} deleted\n"
end