#!/usr/bin/env ruby

require 'rubygems'
require 'getoptlong'

def usage
    puts <<USAGE
== Synopsis

rhc-admin-chk: Check all user applications

== Usage

rhc-admin-ctl-app OPTIONS

Options:
-v|--verbose 
    Print information about each check being performed
-h|--help
    Show Usage info
USAGE
end

opts = GetoptLong.new(
    ["--verbose",          "-v", GetoptLong::NO_ARGUMENT],
    ["--help",             "-h", GetoptLong::NO_ARGUMENT]
)

args = {}
begin
    opts.each{ |k,v| args[k]=v }
rescue GetoptLong::Error => e
    usage
    exit -100
end

verbose = args["--verbose"]


require "/var/www/stickshift/broker/config/environment"

no_error = true
summary = []

node_hash = StickShift::ApplicationContainerProxy.get_all_gears

users = CloudUser.find_all(nil)
mongo_hash = {}
users.each { |user|
  gear_count = 0
  user.applications.each { |app|
    app.group_instances.uniq.each { |gi|
      gi.gears.each { |gear|
        gear_count += 1
        mongo_hash[gear.uuid] = app.name
      }
    }
  }
  if user.consumed_gears != gear_count
    msg = "FAIL - user #{user.login} has a mismatch in consumed gears (#{user.consumed_gears}) and actual gears (#{gear_count})!\n"
    print msg if verbose
    summary << msg
    no_error = false
  else
    print "OK - user #{user.login} has consumed_gears equal to actual gears (#{gear_count})!\n" if verbose
  end
}

# now check
print "Checking application gears in respective nodes :\n" if verbose
mongo_hash.each { |mk,mv|
  print "#{mk}...\t" if verbose
  if not node_hash.has_key? mk
    no_error = false
    print "FAIL\n" if verbose
    summary << "Gear #{mk} in #{mv} does not exist on any node"
  else
    print "OK\n" if verbose
  end
}

# now check reverse
print "Checking node gears in application database:\n" if verbose
node_hash.each { |nk, nv|
  print "#{nk}...\t" if verbose
  if not mongo_hash.has_key? nk
    no_error = false
    print "FAIL\n" if verbose
    summary << "Gear #{nk} exists on node #{nv} but does not exist in mongo database"
  else
    print "OK\n" if verbose
  end
}

puts no_error ? "Success" : "Check failed.\n #{summary.join("\n")}"
exit (no_error ? 0 : 1)
