#!/bin/bash

# Copyright © 2010 Mike McGrath All rights reserved
# Copyright © 2010 Red Hat, Inc. All rights reserved

# This copyrighted material is made available to anyone wishing to use, modify,
# copy, or redistribute it subject to the terms and conditions of the GNU
# General Public License v.2.  This program is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY expressed or implied, including the
# implied warranties of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.  You should have
# received a copy of the GNU General Public License along with this program;
# if not, write to the Free Software Foundation, Inc., 51 Franklin Street,
# Fifth Floor, Boston, MA 02110-1301, USA. Any Red Hat trademarks that are
# incorporated in the source code or documentation are not subject to the GNU
# General Public License and may only be used or replicated with the express
# permission of Red Hat, Inc.

# Executes before configure.  Gives opportunity to make any callbacks to the broker before configure runs.  

# Exit on any errors
set -e

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

function generate_ssh_keys {
    /bin/mkdir -p $APP_DIR/data/.ssh/
    /usr/bin/ssh-keygen -N '' -f $APP_DIR/data/.ssh/jenkins_id_rsa > /dev/null

    /bin/chown root.$uuid -R "$APP_DIR/data/.ssh/"
    chmod 0750 "$APP_DIR/data/.ssh/"
    chmod 0640 "$APP_DIR/data/.ssh/jenkins_id_rsa"
    chmod 0640 "$APP_DIR/data/.ssh/jenkins_id_rsa.pub"
    /usr/bin/chcon -t libra_var_lib_t -l $mcs_level -R "$APP_DIR/data/.ssh/"
}

CART_DIR=${CART_DIR:=/usr/libexec/li/cartridges}
app_type="jenkins-1.4"

source ${CART_DIR}/li-controller/info/lib/util

setup_configure "$1" $2 $3

check_app_dir_doesnt_exist

#
# Setup the base of the application
#

mkdir -p "$APP_DIR"
pushd "$APP_DIR" > /dev/null
create_standard_app_dirs
mkdir logs repo
popd > /dev/null

#
# Generate key pair
#
generate_ssh_keys

public_key=$(cat $APP_DIR/data/.ssh/jenkins_id_rsa.pub)
set -- $public_key
add_ssh_key "$2"

add_broker_auth_key