<?php

/**
 * @file
 * Openshift Partner Program Main File.
 */

/**
 * Implementation of hook_views_api().
 */
function openshift_partner_program_views_api() {
  return array(
    'api' => 2.0,
  );
}

/**
 * Implements hook_theme().
 */
function openshift_partner_program_theme($existing, $type, $theme, $path) {
  return array(
    'openshift_partner_program_portal' => array(
      'template'    => 'templates/openshift_partner_program_portal',
      'arguments'  => array('partner_level' => NULL),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function openshift_partner_program_menu() {
  $items['admin/settings/partner'] = array(
    'title' => 'Administer Partner Program',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_openshift_partner_program_admin'),
    'access callback' => '_openshift_partner_program_user_admin_access',
    'file' => 'openshift_partner_program.admin.inc',
  );
  $items['partner/admin/edit/user/%'] = array(
    'title' => 'Administer Partner Program User',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_openshift_partner_program_user_admin', 4),
    'access callback' => '_openshift_partner_program_user_admin_access',
    'file' => 'openshift_partner_program.admin.inc',
  );
  $items['partner/apply'] = array(
    'title' => 'Apply To Be A Partner',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_openshift_partner_program_apply'),
    'access callback' => '_openshift_partner_program_apply_access',
    'file' => 'openshift_partner_program.page.inc',
  );
  $items['partner/apply/info'] = array(
    'title' => 'Apply To Be A Partner - Upload Info',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_openshift_partner_program_apply_info'),
    'access callback' => '_openshift_partner_program_apply_access',
    'file' => 'openshift_partner_program.page.inc',
  );
  $items['partner/tc'] = array(
    'title' => 'Terms and Conditions',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_openshift_partner_program_tc'),
    'access callback' => '_openshift_partner_program_tc_access',
    'file' => 'openshift_partner_program.page.inc',
  );
  $items['partner/portal'] = array(
    'title' => 'Partner Self Service Portal',
    'type' => MENU_LOCAL_TASK,
    'page callback' => '_openshift_partner_program_portal',
    'access callback' => '_openshift_partner_program_portal_access',
    'file' => 'openshift_partner_program.page.inc',
  );
  $items['partner/portal/upgrade'] = array(
    'title' => 'Upgrade Partner Level',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_openshift_partner_program_portal_upgrade'),
    'access callback' => '_openshift_partner_program_portal_upgrade_access',
    'file' => 'openshift_partner_program.page.inc',
  );
  $items['partner/portal/customer-story'] = array(
    'title' => 'Customer Story',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_openshift_partner_program_portal_customer_story'),
    'access callback' => '_openshift_partner_program_portal_access',
    'file' => 'openshift_partner_program.page.inc',
  );
  $items['partner/portal/request-assistance'] = array(
    'title' => 'Request Assistance',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_openshift_partner_program_portal_request_assistance'),
    'access callback' => '_openshift_partner_program_portal_access',
    'file' => 'openshift_partner_program.page.inc',
  );
  $items['partner/portal/company-info'] = array(
    'title' => 'Upload Company Info',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_openshift_partner_program_portal_company_info'),
    'access callback' => '_openshift_partner_program_portal_access',
    'file' => 'openshift_partner_program.page.inc',
  );
  return $items;
}

/**
 * Implements hook_user().
 *
 * Redirects partner program users to partner agreement or self service
 * portal depending on user state.
 */
function openshift_partner_program_user($op, &$edit, &$account, $category = NULL) {
  global $user;
  $login = ($user->uid == $account->uid && $account->uid > 1);
  if ($op == 'login' && $login) {
    profile_load_profile($account);
    if (isset($account->profile_user_state)) {
      if ($account->profile_user_state == 'New partner') {
        // Go to T & C Page.
        drupal_goto('partner/tc');
      }
      elseif ($account->profile_user_state == 'Active partner') {
        // Go to Self Service Portal Page.
        drupal_goto('partner/portal');
      }
    }
  }
}

/**
 * Access to apply to the partner program form.
 *
 * If the user is a New Partner or Active Partner, they
 * get redirected to the appropriate partner page.
 *
 * @return bool
 *   TRUE iff the user is non anonymous.
 */
function _openshift_partner_program_apply_access() {
  global $user;
  profile_load_profile($user);
  if ($user->profile_user_state == 'New partner') {
    drupal_goto('partner/tc');
  }
  elseif ($user->profile_user_state == 'Active partner') {
    drupal_goto('partner/portal');
  }
  return $user->uid > 0;
}

/**
 * Access to the partner agreement.
 *
 * @return bool
 *   TRUE iff the profile_user_state is New Partner.
 */
function _openshift_partner_program_tc_access() {
  global $user;
  profile_load_profile($user);
  return isset($user->profile_user_state) && $user->profile_user_state == 'New partner';
}

/**
 * Access to the partner program self service portal.
 *
 * @return bool
 *   TRUE iff the profile_user_state is an Active Partner.
 */
function _openshift_partner_program_portal_access() {
  global $user;
  profile_load_profile($user);
  return isset($user->profile_user_state) && $user->profile_user_state == 'Active partner';
}

/**
 * Access to the partner program self service portal.
 *
 * @return bool
 *   TRUE iff the profile_user_state is an Active Partner and
 * profile_partner_level is Ready Partner.
 */
function _openshift_partner_program_portal_upgrade_access() {
  global $user;
  profile_load_profile($user);
  return isset($user->profile_user_state) && $user->profile_partner_level == 'Ready Partner' &&
    _openshift_partner_program_portal_access();
}

/**
 * Is the current user a partner program admin.
 *
 * @return bool
 *   TRUE iff user has partner program admin role.
 */
function _openshift_partner_program_user_admin_access() {
  global $user;
  return in_array('partner program admin', $user->roles) ||
    in_array('administrator', $user->roles);
}

/**
 * Implements hook_mail().
 */
function openshift_partner_program_mail($key, &$message, $params) {
  switch ($key) {
    case 'openshift_partner_program_more_info_required':
      $message['subject'] = t('Additional information is needed for your application to the OpenShift by Red Hat Partner Program');
      $message['body'][] = t('Dear ') . $params['customer_name'];
      $message['body'][] = t('Thank you for your interest in becoming an OpenShift by Red Hat partner.  We have some additional questions before we can proceed with our partnership.');
      $message['body'][] = t('One of our OpenShift by Red Hat Partner Team members will be reaching out with questions.');
      $message['body'][] = t('We look forward to working with you and feel free to let us know if you have any questions.');
      $message['body'][] = t('Regards,');
      $message['body'][] = t('Your OpenShift by Red Hat Partner Team');
      break;

    case 'openshift_partner_program_new_partner':
      $message['subject'] = t('Welcome to the OpenShift by Red Hat Partner Program');
      $message['body'][] = t('Dear ') . $params['customer_name'];
      $message['body'][] = t('Thank you for your interest in becoming an OpenShift by Red Hat partner and we would like to invite you to join the OpenShift by Red Hat Partner program as a ') . $params['partner_level'] . '.';
      $message['body'][] = t('There is one step left in becoming a partner. Login to the partner portal and accept the Partnership Agreement to complete the partnership application. To login:');
      $message['body'][] = t('Visit: http://www.openshift.com/user');
      $message['body'][] = t('Again welcome! Should you have any questions please feel free to email us at openshift-partners@redhat.com');
      $message['body'][] = t('Regards,');
      $message['body'][] = t('Your OpenShift by Red Hat Partner Team');
      break;

    case 'openshift_partner_program_apply_staff':
      $message['subject'] = $params['customer'] . t(' has begun an application to become a partner');
      $message['body'][] = $params['customer'] . t(' has begun the application process to become an OpenShift by Red Hat partner.');
      $message['body'][] = t('They have been sent the following:');
      $message['body'][] = t('Partner Benefit Guide');
      $message['body'][] = t('Quickstart Technical Guide');
      $message['body'][] = t('Cartridge Technical Guide');
      $message['body'][] = t('Link to submit Quickstarts');
      $message['body'][] = t('Please keep an eye out on the alias in case they have any questions.');
      $message['body'][] = t('Thanks.');
      break;

    case 'openshift_partner_program_apply_user':
      $message['subject'] = t('Thank you and Next Steps to become a Red Hat Openshift Partner');
      $message['body'][] = t('Thank you for your interest in becoming an OpenShift by Red Hat partner.');
      $message['body'][] = t('Please review the Partner Benefits documents to decide which partner level is right for you.');
      $message['body'][] = t('To become an OpenShift by Red Hat Ready Partner you must submit an OpenShift Quickstart.  View the Quickstart technical guide to get started now.');
      $message['body'][] = t('To become an OpenShift by Red Hat Advanced Partner you must submit an OpenShift Cartridge.  View the Cartridge technical guide to get started now.');
      $message['body'][] = t('If you have your Quickstart or Cartridge completed please click here to submit now. http://www.openshift.com/partner/apply/info');
      $message['body'][] = t('We look forward to having you onboard as an OpenShift by Red Hat partner.  Feel free to reach out to us at openshift-partners@redhat.com');
      $message['body'][] = t('Regards,');
      $message['body'][] = t('Your OpenShift by Red Hat Partner Team');
      break;

    case 'openshift_partner_program_apply_info':
      $message['subject'] = $params['first'] . ' ' . $params['last'] . t(' has submitted a request for assistance');
      $message['body'][] = t('OpenShift Partner Team-');
      $message['body'][] = t('Please log in and review and approve or request more information within 48 hours for:');
      foreach ($params as $k => $value) {
        $message['body'][] = "$k : $value";
      }
      $message['body'][] = t('You must verify that:');
      $message['body'][] = t('Their Quickstart / Cartridge is acceptable');
      $message['body'][] = t('That they have answered NO to both legal questions and have NOT selected any country in the form.  These are legal requirements and by accepting them as a partner you have verified that they are legally cleared to join.  If they answered YES and/or selected any country, you must reach out to legal to get permission to add them to the program.');
      $message['body'][] = t('If they successfully completed their Quickstart and are legally cleared, please approve and assign them as a Red Hat OpenShift Ready Partner');
      $message['body'][] = t('If they successfully completed their Cartridge and are legally cleared, please approve and assign them as a Red Hat OpenShift Advanced Partner');
      $message['body'][] = t('Thanks.');
      break;

    case 'openshift_partner_program_request_assistance':
      $message['subject'] = $params['company_name'] . t(' has submitted a request for assistance');
      foreach ($params as $k => $value) {
        $message['body'][] = "$k : $value";
      }
      break;

    case 'openshift_partner_program_customer_story':
      $message['subject'] = $params['name'] . t(' has submitted a customer story request');
      foreach ($params as $k => $value) {
        $message['body'][] = "$k : $value";
      }
      break;

    case 'openshift_partner_program_partner_upgrade':
      $message['subject'] = $params['name'] . t(' has submitted a partner level upgrade request');
      foreach ($params as $k => $value) {
        $message['body'][] = "$k : $value";
      }
      break;

    case 'openshift_partner_program_tc':
      $message['subject'] = $params['customer_name'] . t(' has accepted the partner agreement');
      $message['body'] = array(
        t('OpenShift Partner Team-'),
        $params['customer_name'] . t(' has accepted the Partner Agreement and now has access to the self service portal.'),
        t('Thanks.'),
      );
      break;
  }
}

/**
 * Returns the info for the partner with given uid.
 *
 * @param int $uid
 *   The uid of the user to lookup, defaults to current user.
 *
 * @return array|bool|null
 *   The array of info or FALSE if no info.
 */
function openshift_partner_program_partner_info($uid = 0) {
  global $user;
  if ($uid == 0) {
    $uid = $user->uid;
  }
  $node = node_load(array('uid' => $uid, 'type' => 'partner'));
  $result = array();
  if ($node) {
    $result['uid'] = $uid;
    $result['company'] = $node->title;
    $result['company_description'] = $node->body;
    $result['logo'] = $node->picture;
  }
  return $result;
}

/**
 * Updates or inserts program partner info for the user with uid.
 *
 * @param int $uid
 *   The user id.
 * @param string $company
 *   The company name.
 * @param string $company_description
 *   The company description.
 * @param string $logo
 *   The logo path.
 * @param string $expertise_tags
 *   The selected expertise tags.
 *
 * @return bool
 *   TRUE iff insert or update was successful.
 */
function openshift_partner_program_partner_info_upsert($uid, $company, $company_description, $logo, $expertise_tags) {
  $result = db_query("SELECT * FROM {openshift_partner_program_partners} WHERE uid = %d", $uid);
  $exists = db_fetch_array($result);
  if ($exists) {
    $result = db_query("UPDATE {openshift_partner_program_partners} set company = '%s', company_description = '%s', logo = '%s', expertise_tags = '%s'", $company, $company_description, $logo, $expertise_tags);
  }
  else {
    $result = db_query("INSERT INTO {openshift_partner_program_partners} (uid, company, company_description, logo, expertise_tags) VALUES (%d, '%s', '%s', '%s', '%s')", $uid, $company, $company_description, $logo, $expertise_tags);
  }
  return $result;
}

/**
 * Updates or inserts program partner info for the user with uid into node of type partner.
 *
 * @param int $uid
 *   The user id.
 * @param string $company
 *   The company name.
 * @param string $company_description
 *   The company description.
 * @param string $logo
 *   The logo path.
 * @param string $expertise_tags
 *   The selected expertise tags.
 *
 * @return bool
 *   TRUE iff insert or update was successful.
 */
function openshift_partner_program_partner_info_upsert_node($uid, $company, $company_description, $logo, $expertise_tags) {
  $node = node_load(array('uid' => $uid, 'type' => 'partner'));
  $vocab = reset(taxonomy_get_vocabularies('Partner'));
  if (!$node) {
    // No node found.  Need to create.
    $node = new stdClass();
  }
  $node->type = 'partner';
  $node->uid = check_plain($uid);
  $node->status = 1;
  $node->title = check_plain($company);
  $node->body = check_plain($company_description);
  $node->field_logo[0]['value'] = check_plain($logo);

  // Wipe out previous terms if any.
  $node->taxonomy = NULL;

  $tags = explode(",", $expertise_tags);
  foreach ($tags as $val) {
    $term = taxonomy_get_term_by_name($val);
    foreach ($term as $vterm) {
      if ($vterm->vid == $vocab->vid) {
        $node->taxonomy[] = $vterm;
      }
    }
  }

  if ($node = node_submit($node)) {
    node_save($node);
  }
  return $node !== NULL;
}

/**
 * Returns an array of partner info.
 *
 * @return array
 *   Array of partner info or NULL if no partners.
 */
function openshift_partner_program_partners_list() {
  $result = db_query("SELECT * FROM {openshift_partner_program_partners}");
  $modified_row = array();
  $augmented_result = array();
  while ($row = db_fetch_array($result)) {
    // Check to make sure user still exists.
    $exists = user_load(array('uid' => $row['uid']));
    if ($exists) {
      foreach ($row as $key => $value) {
        if ($key == 'expertise_tags' && $value == '') {
          $modified_row[$key] = t('partner');
        }
        elseif ($key == 'expertise_tags') {
          $modified_row[$key] = t('partner') . ",$value";
        }
        else {
          $modified_row[$key] = $value;
        }
      }
      $augmented_result[] = $modified_row;
    }
  }
  return $augmented_result;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Partner program and user state can only be set in the admin interface.
 * Removing from the profile.
 */
function openshift_partner_program_form_user_profile_form_alter(&$form, &$form_state) {
  unset($form['Partner Program']);
}

/**
 * Implements hook_init().
 *
 * Restricts partner/portal paths to Active partner users.
 */
function openshift_partner_program_init() {
  global $user;
  $path = $_REQUEST['q'];
  if (!strncmp($path, 'partner/portal', strlen('partner/portal'))) {
    profile_load_profile($user);
    if ($user->profile_user_state != 'Active partner' && !_openshift_partner_program_user_admin_access()) {
      drupal_access_denied();
    }
  }

}
