#!/bin/bash

[ ! -z "$PSQL_LIB_UTIL" ] && return 0
PSQL_LIB_UTIL=true

function start_memcached {
    MEMCACHED_DIR=${PSQL_DIR:-"$APP_HOME/memcached-1.4/"}
    super_run_as_user "$MEMCACHED_DIR/${application}_memcached_ctl.sh start"
    wait_to_start
}

function wait_to_start {
    i=0
    phpcode="exit((TRUE == memcache_connect('127.250.0.1', 11211))? 0 : 1);"
    while (( php -r "$phpcode" > /dev/null 2>&1) || [ ! -f ${MEMCACHED}/pid/memcached.pid ]) && [ $i -lt 10 ]
    do
        sleep 1
        i=$(($i + 1))
    done
}


function stop_memcached {
    MEMCACHED_DIR=${PSQL_DIR:-"$APP_HOME/memcached-1.4/"}
    super_run_as_user "$MEMCACHED_DIR/${application}_memcached_ctl.sh stop"
}

function start_memcached_as_user {
    ${OPENSHIFT_MEMCACHED_CTL_SCRIPT} start
}

function stop_memcached_as_user {
    ${OPENSHIFT_MEMCACHED_SCRIPT} stop
    sleep 1
}

function wait_to_start_as_user {
    if [ -n "$OPENSHIFT_MEMCACHED_SCRIPT" ]
    then
        i=0
        sleep 1
        phpcode="exit((TRUE == memcache_connect('127.250.0.1', 11211))? 0 : 1);"
        while (( php -r "$phpcode" > /dev/null 2>&1) || [ ! -f ${MEMCACHED}/pid/memcached.pid ]) && [ $i -lt 10 ]
        do
            sleep 1
            i=$(($i + 1))
        done
    fi
}
