#!/bin/bash
set -e
function quit {
    echo $1
    exit 5
}

[ $# -eq 1 ] || quit "provide a version number"

version=$1

[ -d "li-$version" ] && quit "li-$version already exists"

cp -adv li li-$version
rm -rf li-$version/.git
tar -czvf ~/rpms/SOURCES/li-$version.tar.gz li-$version
cp li-$version/packaging/li.spec ~/rpms/SPECS
sed -i "s/Version:.*/Version: $version/" ~/rpms/SPECS/li.spec
rpmbuild -bs li-$version/packaging/li.spec
mock -r li-6-x86_64 /home/mmcgrath/rpms/SRPMS/li-$version-1el5.src.rpm
rm -rf li-$version
