#!/usr/bin/env oo-ruby

require 'rubygems'
require 'getoptlong'

def usage
    puts <<USAGE
== Synopsis

rhc-admin-stale-dns: Purge stale DNS records

== Usage

rhc-admin-stale-dns OPTIONS

Options:
-a|--application <Name>
    Application name to destroy (optional)
-h|--help:
    Show Usage info

== Example

To purge the following applications:
foo-foo1, bar-foo1, baz-foo1, uno-foo2, dos-foo2, tres-foo2

rhc-admin-stale-dns -a foo-foo1 -a bar-foo1 -a uno-foo2 -a dos-foo2


== Warning

This purges information directly out of DNS without any sanity checks
to ensure its the right information.  Excercise extreme caution.

USAGE
  exit 255
end

opts = GetoptLong.new(
    ["--application",      "-a", GetoptLong::OPTIONAL_ARGUMENT],
    ["--help",             "-h", GetoptLong::NO_ARGUMENT]
)

applications=[]
begin
  opts.each do |opt,arg|
    case opt
    when '--help'
      usage
    when '--application'
      app, ns = arg.split("-")
      if app.nil? or ns.nil?
        usage
      end
      applications << [app, ns]
    end
  end
rescue GetoptLong::Error => e
  usage
end

require "/var/www/openshift/broker/config/environment"
# Disable analytics for admin scripts
Rails.configuration.analytics[:enabled] = false

dns = OpenShift::DnsService.instance
begin
  applications.each do |app|
    puts "Deregister application: #{app[0]} in #{app[1]}"
    dns.deregister_application(app[0], app[1])
  end

  dns.publish
ensure
  dns.close
end
