<?php

include_once('user_profile.features.inc');

function user_profile_filter($op, $delta=0, $format=-1, $text='', $cache_id=0) {
  switch ($op) {
    case 'list':
      return array(0 => t('Bootstrap Markup'), 1 => t('Code-fenced blocks'));
    case 'description':
      switch ($delta) {
        case 1:
          return t('Transforms code fenced blocks (```) to <blockquote> for use with GeSHiFilter');
        case 0:
          return t('Adds standard bootstrap classes to base markup');
      }
    case 'prepare':
      switch ($delta) {
        case 1:
          return preg_replace('/`{3}(?:(.*$)\n)?([\s\S]+?)`{3}/m', "<blockcode language=\"$1\">$2</blockcode>", $text);
        default:
          return $text;
      }
    case 'process':
      switch ($delta) {
        case 0:
          return str_ireplace('<table>', '<table class="table">', $text);
        default:
          return $text;
      }
    default:
      return $text;
  }
}

/**
 * DEPRECATED - these are no longer used
 *
 */
function user_profile_block($op = 'list', $delta = '', $edit = array()) {
  global $user;
  switch ($op) {
  case 'list':
    $blocks['community-messaging'] = array(
      'info' => t('Community Messaging')
    );
    $blocks['developer-center-messaging'] = array(
      'info' => t('Developer Center Messaging')
    );
    $blocks['learn-more-messaging'] = array(
      'info' => t('Learn More Messaging')
    );
    $blocks['get-started-messaging'] = array(
      'info' => t('Get Started Messaging')
    );
    return $blocks;
  case 'configure':
    return array();
  case 'save':
    return;
  case 'view':
    switch ($delta) {
    case 'get-started-messaging':
      $block['content'] = 
        '<div class="messaging"><div class="container">'.
        '<div class="primary headline">Launch your <strong>Big Idea</strong> in minutes</div>' .
        '<div class="secondary">OpenShift is a next generation application hosting environment. Read on to see how easy it is to get started in the cloud.</div>' .
        '</div></div>';
      break;
    case 'learn-more-messaging':
      $block['content'] = 
        '<div class="messaging"><div class="container">'.
        '<div class="primary headline">Take your <strong>Apps</strong> to the Cloud</div>' .
        '<div class="secondary">OpenShift is a next generation application hosting environment. Read on to see how it can help you achieve your application goals.</div>' .
        '</div></div>';
      break;
    case 'home-messaging':
      $block['content'] = 
        '<div class="messaging messaging-home"><div class="container">'.
        '<h1 class="primary headline">Build, run, &amp; scale apps fast '.
        '<small>in an easy-to-use cloud environment</small></h1>'.
        '</div></div>';
      break;
    case 'developer-center-messaging':
      $block['content'] = 
        '<div class="messaging"><div class="container">'.
        '<div class="primary headline">Build on <strong>OpenShift</strong></div>' .
        '<div class="secondary">Find the help you need in the Developer Center to launch your biggest ideas.</div>' .
        '</div></div>';
      break;
    case 'community-messaging':
      $block['content'] = 
        '<div class="messaging"><div class="container">'.
        '<div class="primary headline">Join the <strong>OpenShift Community</strong></div>' .
        '<div class="secondary">This is the place to learn and engage with OpenShift users and developers. Sign in to participate</div>' .
        '</div></div>';
      break;
    }
    return $block;
  }
}

function user_profile_block_call_to_action() {
  if (user_is_logged_in()) {
    return 
      '<a class="action-call" href="/app/console">'.
        '<div>Open the <strong>OpenShift</strong> Console</div>'.
        '<div class="highlight-arrow">&gt;</div>'.
      '</a>';
  }
  else {
    return 
      '<a class="action-call" href="/app/account/new">'.
        '<div>Sign up to try <strong>OpenShift</strong></div>'.
        '<div class="highlight-arrow">&gt;</div>'.
      '</a>';
  }
}
