#!/bin/bash

[ ! -z "$LI_CONTROLLER_LIB_SELINUX" ] && return 0
LI_CONTROLLER_LIB_SELINUX=true

function openshift_mcs_level() {
    SETSIZE=1023
    TIER=$SETSIZE

    ORD=$1
    while [ $ORD -gt $(($TIER)) ] ; do
    ORD=$(($ORD - $TIER))
    TIER=$(($TIER - 1))
    done
    TIER=$(($SETSIZE - $TIER))
    echo s0:c$TIER,c$(($ORD + $TIER))
}