#!/bin/bash

# Copyright © 2010 Mike McGrath All rights reserved
# Copyright © 2010 Red Hat, Inc. All rights reserved

# This copyrighted material is made available to anyone wishing to use, modify,
# copy, or redistribute it subject to the terms and conditions of the GNU
# General Public License v.2.  This program is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY expressed or implied, including the
# implied warranties of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.  You should have
# received a copy of the GNU General Public License along with this program;
# if not, write to the Free Software Foundation, Inc., 51 Franklin Street,
# Fifth Floor, Boston, MA 02110-1301, USA. Any Red Hat trademarks that are
# incorporated in the source code or documentation are not subject to the GNU
# General Public License and may only be used or replicated with the express
# permission of Red Hat, Inc.

# Start the application httpd instance

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Start a running application"

    echo "$0 $@" | logger -p local0.notice -t libra_httpd_start
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 -o $# -eq 4 ] || print_help

CART_DIR=/usr/libexec/li/cartridges
source ${CART_DIR}/abstract/info/lib/util

setup_basic_hook "$1" $2 $3

uuid=$3
uid=`id -u $uuid`

function remove_port {
  uuid=$1
  uid=`id -u $uuid`

  source "/var/lib/libra/${uuid}/.env/OPENSHIFT_INTERNAL_IP"
  source "/var/lib/libra/${uuid}/.env/OPENSHIFT_INTERNAL_PORT"
  source "/var/lib/libra/${uuid}/.env/OPENSHIFT_APP_DNS"

  for port_file in `/bin/ls /var/lib/libra/${uuid}/.env/OPENSHIFT_*_PUB_PORT 2> /dev/null`
  do
    source "$port_file"
  done

  target="$OPENSHIFT_INTERNAL_IP:$OPENSHIFT_INTERNAL_PORT"

  for proxy_port in "${!OPENSHIFT_PUB_PORT[@]}"
  do
    if [ "$target" == "${OPENSHIFT_PUB_PORT[$proxy_port]}" ]
    then
      client_message "Disabling port: $OPENSHIFT_APP_DNS:$proxy_port"
      service libra-proxy setproxy $proxy_port del
      rm -f $APP_HOME/.env/OPENSHIFT_${proxy_port}_PUB_PORT
      exit 0
    fi
  done
  client_error "Proxy for $target not found!"
  exit 67
}

remove_port $uuid
