#!/bin/bash

# Copyright © 2010 Mike McGrath All rights reserved
# Copyright © 2010 Red Hat, Inc. All rights reserved

# This copyrighted material is made available to anyone wishing to use, modify,
# copy, or redistribute it subject to the terms and conditions of the GNU
# General Public License v.2.  This program is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY expressed or implied, including the
# implied warranties of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.  You should have
# received a copy of the GNU General Public License along with this program;
# if not, write to the Free Software Foundation, Inc., 51 Franklin Street,
# Fifth Floor, Boston, MA 02110-1301, USA. Any Red Hat trademarks that are
# incorporated in the source code or documentation are not subject to the GNU
# General Public License and may only be used or replicated with the express
# permission of Red Hat, Inc.

# Deploy httpd proxy

# Exit on any errors
set -e

CART_DIR=/usr/libexec/li/cartridges

source ${CART_DIR}/li-controller/info/lib/util
source ${CART_DIR}/li-controller/info/lib/selinux
source ${CART_DIR}/li-controller/info/lib/apache
source ${CART_DIR}/li-controller/info/lib/network

load_node_conf

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done

[ $# -eq 3 ] || print_help

namespace=`basename $2`
application="$1"
uuid=$3

setup_basic_vars

. $APP_HOME/.env/OPENSHIFT_APP_TYPE

CART_INFO_DIR=$CART_DIR/$OPENSHIFT_APP_TYPE/info

if ! [ -f $APP_HOME/.env/OPENSHIFT_INTERNAL_IP ]
then
  #
  # Find an open localhost IP
  #
  IP=`find_open_ip $uid $uuid`
  echo "export OPENSHIFT_INTERNAL_IP='$IP'" > $APP_HOME/.env/OPENSHIFT_INTERNAL_IP
  if [ -f $CART_INFO_DIR/bin/deploy_httpd_config.sh ]
  then
    $CART_INFO_DIR/bin/deploy_httpd_config.sh $application $uuid $IP
  fi
  runuser --shell /bin/sh "$uuid" -c "runcon -t libra_t -l $mcs_level ${CART_DIR}/li-controller/info/bin/redeploy_config_dir.sh"
  
  if [ -f $APP_HOME/metrics-0.1 ]
  then
      METRICS_IP=`embedded_find_open_ip $uid $APP_HOME`
      echo "export OPENSHIFT_METRICS_IP='$METRICS_IP'" > $APP_HOME/.env/OPENSHIFT_METRICS_IP
      $CART_DIR/embedded/metrics-0.1/info/bin/deploy_httpd_config.sh $application $uuid $METRICS_IP
      $CART_DIR/embedded/metrics-0.1/info/bin/deploy_httpd_proxy.sh $application $namespace $uuid $METRICS_IP
  fi
  if [ -f $APP_HOME/phpmyadmin-3.4 ]
  then
      PHPMYADMIN_IP=`embedded_find_open_ip $uid $APP_HOME`
      echo "export OPENSHIFT_PHPMYADMIN_IP='$PHPMYADMIN_IP'" > $APP_HOME/.env/OPENSHIFT_PHPMYADMIN_IP
      $CART_DIR/embedded/phpmyadmin-3.4/info/bin/deploy_httpd_config.sh $application $uuid $PHPMYADMIN_IP
      $CART_DIR/embedded/phpmyadmin-3.4/info/bin/deploy_httpd_proxy.sh $application $namespace $uuid $PHPMYADMIN_IP
  fi
  if [ -f $APP_HOME/mysql-5.1 ]
  then
      echo "export OPENSHIFT_DB_HOST='$IP'" > $APP_HOME/.env/OPENSHIFT_DB_HOST
      
      . $APP_HOME/.env/OPENSHIFT_DB_PASSWORD
      if [ "$OPENSHIFT_DB_PASSWORD" = "NOT_AVAILABLE" ]
      then
          echo "export OPENSHIFT_DB_URL='mysql://admin@$IP:3306/'" > $APP_HOME/.env/OPENSHIFT_DB_URL
      else
          echo "export OPENSHIFT_DB_URL='mysql://admin:$OPENSHIFT_DB_PASSWORD@$IP:3306/'" > $APP_HOME/.env/OPENSHIFT_DB_URL
      fi
      
      $CART_DIR/embedded/mysql-5.1/info/bin/deploy_httpd_config.sh $application $uuid $IP
      $CART_DIR/embedded/mysql-5.1/info/bin/deploy_httpd_proxy.sh $application $namespace $uuid $IP
  fi
  
  
fi
. $APP_HOME/.env/OPENSHIFT_INTERNAL_IP

#
# Create virtualhost definition for apache
#
export CART_INFO_DIR
if [ -f $CART_INFO_DIR/bin/deploy_httpd_proxy.sh ]
then
  $CART_INFO_DIR/bin/deploy_httpd_proxy.sh $application $namespace $uuid $OPENSHIFT_INTERNAL_IP
else
  $CART_DIR/abstract/info/bin/deploy_httpd_proxy.sh $application $namespace $uuid $OPENSHIFT_INTERNAL_IP
fi

restart_httpd_graceful